Repository strictdoc-project/strictdoc, pull requests merged in 2022-05, with the labels that each got.

#682 tasks: fix the "The command line is too long." issue on Windows
  tasks.py
Labels: development tools, code climate

#688 tests/integration: Python version of 'cp' and 'rm' to make them portable
  tests/integration/commands/export/09_does_not_find_documents_in_output_folder/test.itest
  tests/integration/commands/export/html/incremental_generation/03_when_new_child_generate_parents/test.itest
  tests/integration/commands/export/options/--no-parallelization/test.itest
  tests/integration/cp.py
  tests/integration/lit.cfg
  tests/integration/rm.py
Labels: development tools, code climate

#690 tests/integration: improve rm.py
  tests/integration/commands/export/options/--no-parallelization/test.itest
  tests/integration/rm.py
Labels: development tools, code climate

#691 tasks: on Windows: detect if Bash is available
  tasks.py
Labels: development tools, code climate

#693 tests/integration: move away from a grep-based test
  tests/integration/commands/export/html/file_traceability/05_multiple_files_per_requirement/test.itest
Labels: testing, code climate

#695 grammar: New option: REQUIREMENT_HAS_TITLE
  strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
  strictdoc/backend/reqif/import_/reqif_to_sdoc_factory.py
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/models/document_config.py
  strictdoc/backend/sdoc/writer.py
  tests/unit/helpers/test_document_builder.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
  tests/unit/strictdoc/backend/sdoc/validations/test_requirement.py
Labels: Data model

#696 grammar: REQUIREMENT_HAS_TITLE -> REQUIREMENT_IN_TOC
  strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
  strictdoc/backend/reqif/import_/reqif_to_sdoc_factory.py
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/models/document_config.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/document_iterator.py
  tests/unit/helpers/test_document_builder.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
  tests/unit/strictdoc/backend/sdoc/validations/test_requirement.py
Labels: Data model

#697 Code climate: fix cyclic import in strictdoc.backend.sdoc.processor
  strictdoc/backend/sdoc/include_reader.py
  strictdoc/backend/sdoc/models/constants.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/reader.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_includes.py
Labels: Code climate

#699 bugfix: AttributeError: 'NoneType' object has no attribute 'required'
  strictdoc/backend/sdoc/models/type_system.py
  strictdoc/backend/sdoc/validations/requirement.py
  tests/integration/per_document_grammar/validation/05_unexpected_field_outside_grammar/test.itest
Labels: Bug, Data model

#702 tasks: switch to python3 everywhere for now
  tasks.py
Labels: Development tools

#703 backend/sdoc: fix handling of LEVEL: None for composite requirements
  strictdoc/__init__.py
  strictdoc/backend/sdoc/models/requirement.py
  strictdoc/backend/sdoc/processor.py
Labels: Data model

#705 export/HTML: UI: fix grid in .table-view > .requirement_meta
  strictdoc/export/html/_static/_requirement-tree.css
  strictdoc/export/html/_static/_requirement.css
Labels: UI/UX, Frontend

#708 docs: move CONTRIBUTING to .sdoc
  CONTRIBUTING.md
  docs/sphinx/source/index.rst
  docs/sphinx/source/strictdoc-1-user-manual.rst
  docs/sphinx/source/strictdoc-2-development-plan.rst
  docs/sphinx/source/strictdoc-3-requirements.rst
  docs/sphinx/source/strictdoc-4-design.rst
  docs/sphinx/source/strictdoc-5-backlog.rst
  docs/sphinx/source/strictdoc-6-contributing.rst
  docs/strictdoc-1-user-manual.sdoc
  docs/strictdoc-2-development-plan.sdoc
  docs/strictdoc-3-requirements.sdoc
  docs/strictdoc-4-design.sdoc
  docs/strictdoc-5-backlog.sdoc
  docs/strictdoc-6-contributing.sdoc
  docs/strictdoc-html/strictdoc-html/_static/_content.css
  docs/strictdoc-html/strictdoc-html/_static/_requirement-tree.css
  docs/strictdoc-html/strictdoc-html/_static/_requirement.css
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-1-user-manual-DEEP-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-1-user-manual-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-1-user-manual-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-1-user-manual.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-2-development-plan-DEEP-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-2-development-plan-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-2-development-plan-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-2-development-plan.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-3-requirements-DEEP-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-3-requirements-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-3-requirements-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-3-requirements.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-4-design-DEEP-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-4-design-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-4-design-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-4-design.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-5-backlog-DEEP-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-5-backlog-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-5-backlog-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-5-backlog.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-6-contributing-DEEP-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-6-contributing-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-6-contributing-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-6-contributing.html
  docs/strictdoc-html/strictdoc-html/index.html
  docs/strictdoc-html/strictdoc-html/requirements_coverage.html
Labels: Documentation

#712 docs: extract F.A.Q. to a separate document
  docs/sphinx/source/index.rst
  docs/sphinx/source/strictdoc-1-user-manual.rst
  docs/sphinx/source/strictdoc-7-faq.rst
  docs/strictdoc-1-user-manual.sdoc
  docs/strictdoc-7-faq.sdoc
  docs/strictdoc-html/strictdoc-html/_static/_content.css
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-1-user-manual-DEEP-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-1-user-manual-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-1-user-manual-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-1-user-manual.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-2-development-plan-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-3-requirements-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-4-design-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-5-backlog-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-6-contributing-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-7-faq-DEEP-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-7-faq-TABLE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-7-faq-TRACE.html
  docs/strictdoc-html/strictdoc-html/docs/strictdoc-7-faq.html
  docs/strictdoc-html/strictdoc-html/index.html
  docs/strictdoc-html/strictdoc-html/requirements_coverage.html
  tests/integration/self_testing/commands/export/01_strictdoc_smoke_test/test.itest
  tests/integration/self_testing/commands/passthrough/01_hello_world/test.itest
Labels: Documentation
