Repository strictdoc-project/strictdoc, pull requests merged in 2023-10, with the labels that each got.

#1326 tasks: fix the PyInstaller issue (temporary workaround)
  .github/workflows/periodic-integration-test.yml
  docs/strictdoc_01_user_guide.sdoc
  tasks.py
  tox.ini
Labels: Bug, Infrastructure / Developer experience, PyInstaller

#1325 tasks: fix the PyInstaller issue
  .github/workflows/periodic-integration-test.yml
  developer/pyinstaller_hooks/hook-yaml.py
Labels: PyInstaller

#1327 UI: update_requirement: fix an edge case with fields conversion
  strictdoc/__init__.py
  strictdoc/core/commands/update_requirement.py
  strictdoc/core/traceability_index.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/templates/components/requirement_form/row_with_relation.jinja
  tests/unit/strictdoc/core/transforms/test_update_requirement.py
Labels: UI/UX, Core roadmap

#1328 tests/end2end: improve the robustness of one test that can be flaky
  tests/end2end/screens/document/edit_requirement/_requirement_relations/update_requirement_add_three_links/test_case.py
Labels: Infrastructure / Developer experience, SQA, Second roadmap

#1334 CI: bring back the previously failing tests
  tests/end2end/screens/document/update_requirement/_requirement_relations/update_requirement_add_second_child_link_with_role/test_case.py
  tests/end2end/screens/document/update_requirement/_requirement_relations/update_requirement_add_second_parent_link_with_role/test_case.py
Labels: Bug, SQA, Second roadmap

#1335 commands/manage_autoiud_command: generate UID across documents
  strictdoc/__init__.py
  strictdoc/cli/cli_arg_parser.py
  strictdoc/cli/command_parser_builder.py
  strictdoc/cli/main.py
  strictdoc/commands/manage_autouid_command.py
  strictdoc/core/analyzers/document_stats.py
  strictdoc/core/analyzers/document_uid_analyzer.py
  strictdoc/core/project_config.py
  strictdoc/server/routers/main_router.py
  tests/end2end/project_options/html_assets_strictdoc_dir/01_option_specified_project_index/test_01_option_specified.py
  tests/end2end/project_options/html_assets_strictdoc_dir/03_option_specified_requirements_coverage/test_03_option_specified_requirements_coverage.py
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_first_and_second_requirement/__init__.py
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_first_and_second_requirement/expected_output/document.sdoc
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_first_and_second_requirement/input/document.sdoc
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_first_and_second_requirement/test_case.py
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_first_and_second_requirement_two_different_documents/__init__.py
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_first_and_second_requirement_two_different_documents/expected_output/document.sdoc
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_first_and_second_requirement_two_different_documents/input/document.sdoc
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_first_and_second_requirement_two_different_documents/test_case.py
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_when_requirement_with_another_prefix_exists/__init__.py
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_when_requirement_with_another_prefix_exists/expected_output/document.sdoc
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_when_requirement_with_another_prefix_exists/expected_output/document2.sdoc
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_when_requirement_with_another_prefix_exists/input/document.sdoc
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_when_requirement_with_another_prefix_exists/input/document2.sdoc
  tests/end2end/screens/document/create_requirement/_autouid/create_requirement_generate_autouid_when_requirement_with_another_prefix_exists/test_case.py
  tests/integration/commands/manage/auto-uid/requirement_uids/04_requirement_prefix_section_level/input.expected.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/07_works_across_documents_default_prefix/input1.expected.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/07_works_across_documents_default_prefix/input1.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/07_works_across_documents_default_prefix/input2.expected.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/07_works_across_documents_default_prefix/input2.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/07_works_across_documents_default_prefix/test.itest
  tests/integration/commands/manage/auto-uid/requirement_uids/08_works_across_documents_custom_prefix/input1.expected.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/08_works_across_documents_custom_prefix/input1.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/08_works_across_documents_custom_prefix/input2.expected.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/08_works_across_documents_custom_prefix/input2.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/08_works_across_documents_custom_prefix/input3.expected.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/08_works_across_documents_custom_prefix/input3.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/08_works_across_documents_custom_prefix/test.itest
  tests/integration/commands/manage/auto-uid/section_uids/01_generates_section_uids/test.itest
  tests/integration/commands/manage/auto-uid/section_uids/02_identical_titles_get_numeric_postfix/test.itest
Labels: Feature, Core roadmap

#1336 backend/sdoc: start to recognize requirement RELATIONS: in SDoc
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/models/requirement.py
  strictdoc/backend/sdoc/writer.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_relations_migrate_from_refs.py
Labels: Feature, Core roadmap

#1341 backend/sdoc: print deprecation warnings when REFS are used
  strictdoc/__init__.py
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/models/requirement.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/reader.py
  strictdoc/backend/sdoc/writer.py
  tests/end2end/screens/document/create_requirement/_relations/create_requirement_with_relation_and_role_to_existing_requirement/expected_output/document.sdoc
  tests/end2end/screens/document/create_requirement/_relations/create_requirement_with_relation_to_existing_requirement/expected_output/document.sdoc
  tests/end2end/screens/document/create_requirement/_relations/create_requirement_with_relation_to_existing_requirement_in_another_document/expected_output/document2.sdoc
  tests/end2end/screens/document/update_requirement/_requirement_relations/update_requirement_add_one_child_link_with_role/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_requirement_relations/update_requirement_add_one_link/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_requirement_relations/update_requirement_add_one_parent_link_with_role/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_requirement_relations/update_requirement_add_three_links/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_requirement_relations/update_requirement_add_three_links/test_case.py
  tests/integration/deprecations/refs_replaced_with_relations/01_show_warning_when_refs_are_present/input.sdoc
  tests/integration/deprecations/refs_replaced_with_relations/01_show_warning_when_refs_are_present/test.itest
  tests/integration/deprecations/refs_replaced_with_relations/02_do_not_show_warning_when_refs_are_not_present/input.sdoc
  tests/integration/deprecations/refs_replaced_with_relations/02_do_not_show_warning_when_refs_are_not_present/test.itest
  tests/integration/deprecations/refs_replaced_with_relations/03_recommended_migration_example_works/input.sdoc
  tests/integration/deprecations/refs_replaced_with_relations/03_recommended_migration_example_works/test.itest
  tests/integration/deprecations/refs_replaced_with_relations/10_raise_error_if_refs_is_string_in_grammar/input.sdoc
  tests/integration/deprecations/refs_replaced_with_relations/10_raise_error_if_refs_is_string_in_grammar/test.itest
  tests/integration/deprecations/refs_replaced_with_relations/11_raise_error_if_refs_is_string_in_requirement/input.sdoc
  tests/integration/deprecations/refs_replaced_with_relations/11_raise_error_if_refs_is_string_in_requirement/test.itest
  tests/integration/deprecations/refs_replaced_with_relations/20_show_warning_when_refs_or_relations_are_not_last/input.sdoc
  tests/integration/deprecations/refs_replaced_with_relations/20_show_warning_when_refs_or_relations_are_not_last/test.itest
  tests/integration/deprecations/refs_replaced_with_relations/21_do_not_show_warning_when_refs_or_relations_are_last/input.sdoc
  tests/integration/deprecations/refs_replaced_with_relations/21_do_not_show_warning_when_refs_or_relations_are_last/test.itest
Labels: Feature, Core roadmap

#1347 docs: document RELATIONS, deprecate REFS
  docs/strictdoc_01_user_guide.sdoc
  drafts/requirements/20_high_level/21_DO178.sdoc
  strictdoc/__init__.py
  strictdoc/core/traceability_index.py
  strictdoc/core/transforms/section.py
  strictdoc/export/html/templates/components/node/index.jinja
  tests/integration/options/options_per_section/LEVEL/02_level_is_None_for_requirements/test.itest
Labels: Documentation, Core roadmap

#1354 docs: add the Roadmap diagram export (2023-11-21)
  docs/_assets/StrictDoc_Roadmap.drawio.svg
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_03_development_plan.sdoc
  docs/strictdoc_11_developer_guide.sdoc
Labels: Documentation, Second roadmap

#1361 Bump version to 0.0.45
  .github/workflows/release.yml
  docs/_assets/StrictDoc_Roadmap.drawio.png
  docs/sphinx/source/_assets/StrictDoc_Roadmap.drawio.png
  docs/sphinx/source/_assets/theme_overrides.css
  docs/sphinx/source/_static/logo.jpg
  docs/sphinx/source/conf.py
  docs/sphinx/source/strictdoc_01_user_guide.rst
  docs/sphinx/source/strictdoc_03_development_plan.rst
  docs/sphinx/source/strictdoc_11_developer_guide.rst
  docs/strictdoc_03_development_plan.sdoc
  strictdoc/__init__.py
  tasks.py
Labels: Documentation, Core roadmap

#1372 Bump version to 0.0.46
  strictdoc/__init__.py
Labels: Bug, Second roadmap

#1376 tasks: server: optional --config parameter
  tasks.py
Labels: Infrastructure / Developer experience, Second roadmap

#1381 tests/end2end: update requirement: add a link to section using copy and paste
  strictdoc/export/html/_static/controllers/anchor_controller.js
  tests/end2end/e2e_case.py
  tests/end2end/helpers/components/node/section.py
  tests/end2end/screens/document/_cross_cutting/anchors/section/update_section_add_link_to_existing_section_anchor_from_clipboard/__init__.py
  tests/end2end/screens/document/_cross_cutting/anchors/section/update_section_add_link_to_existing_section_anchor_from_clipboard/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/anchors/section/update_section_add_link_to_existing_section_anchor_from_clipboard/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/anchors/section/update_section_add_link_to_existing_section_anchor_from_clipboard/test_case.py
  tests/end2end/screens/document/_cross_cutting/anchors/section/update_section_add_second_anchor/__init__.py
  tests/end2end/screens/document/_cross_cutting/anchors/section/update_section_add_second_anchor/test_case.py
  tests/end2end/test_helpers.py
Labels: SQA, Second roadmap

#1383 cli: version command with "-v" and "--version"
  strictdoc/__init__.py
  strictdoc/cli/command_parser_builder.py
  tests/integration/commands/version/01_print_version/test.itest
Labels: Second roadmap

#1401 Code climate: tasks: build tox, mypy, pytest, ruff into build/
  tasks.py
  tox.ini
Labels: Code climate, Infrastructure / Developer experience, Second roadmap

#1402 tests/end2end: try to fix flaky test problem by changing the custom port
  pyproject.toml
  tests/end2end/project_options/project_title/01_option_not_specified/test_case.py
  tests/end2end/project_options/project_title/02_option_specified/test_case.py
  tests/end2end/project_options/server_host/01_option_not_specified/test_case.py
  tests/end2end/project_options/server_host/02_option_specified/test_case.py
Labels: Code climate, Infrastructure / Developer experience, SQA, Second roadmap

#1403 gitignore: add *.local.toml
  .gitignore
Labels: Infrastructure / Developer experience, Second roadmap

#1404 Code climate: limit mypy to the lowest Python of 3.7
  tasks.py
Labels: Code climate, Infrastructure / Developer experience, Second roadmap
