Repository strictdoc-project/strictdoc, pull requests merged in 2024-03, with the labels that each got.

#1676 Code climate: update to new Ruff settings
  ruff.toml
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/reqif/p11_polarion/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/core/document_tree.py
  strictdoc/core/project_config.py
  strictdoc/core/traceability_index.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/section.py
  strictdoc/core/transforms/update_grammar.py
  strictdoc/core/transforms/update_grammar_element.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/generators/view_objects/source_file_view_object.py
  strictdoc/export/html/renderers/link_renderer.py
  strictdoc/export/html/tools/html_embedded.py
  strictdoc/export/json/json_generator.py
  strictdoc/export/spdx/spdx_generator.py
  strictdoc/git/change.py
  strictdoc/git/project_diff_analyzer.py
  strictdoc/server/routers/main_router.py
  tasks.py
  tests/end2end/helpers/constants.py
  tests/end2end/server.py
Labels: Second roadmap

#1675 server: requirement_form_object: adapt to custom elements in the last places
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/templates/screens/document/document/frame_requirement_form.jinja
  strictdoc/server/routers/main_router.py
  tests/end2end/helpers/components/node/requirement.py
  tests/end2end/screens/document/create_requirement/_arbitrary_elements/create_requirement_create_test_element_with_custom_field_in_top_level_document/__init__.py
  tests/end2end/screens/document/create_requirement/_arbitrary_elements/create_requirement_create_test_element_with_custom_field_in_top_level_document/expected_output/document.sdoc
  tests/end2end/screens/document/create_requirement/_arbitrary_elements/create_requirement_create_test_element_with_custom_field_in_top_level_document/input/document.sdoc
  tests/end2end/screens/document/create_requirement/_arbitrary_elements/create_requirement_create_test_element_with_custom_field_in_top_level_document/test_case.py
Labels: Core roadmap

#1678 server: several validation messages: requirement -> node
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/core/query_engine/query_object.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  tests/end2end/screens/document/create_requirement/_validation/create_requirement_validate_no_statement/test_case.py
  tests/end2end/screens/document/create_requirement/_validation/create_requirement_validate_uid_already_exists/test_case.py
  tests/end2end/screens/document/update_requirement/_validation/update_requirement_empty_statement/test_case.py
Labels: UI/UX, Core roadmap

#1679 export/dot: minor improvements to the layout
  strictdoc/export/dot/document_dot_generator.py
  strictdoc/export/dot/templates/profile1/legend.dot
  strictdoc/export/dot/templates/profile1/requirement.dot
  tasks.py
Labels: Second roadmap

#1680 export/html: highlight current document
  strictdoc/export/html/templates/screens/document/_shared/project_tree.jinja
Labels: UI/UX, Second roadmap

#1682 Bump version to 0.0.49a6
  strictdoc/__init__.py
Labels: Second roadmap

#1689 export/html: update form error styles for fields and field groups (driven by HUMAN_TITLE)
  strictdoc/export/html/_static/element.css
  strictdoc/export/html/_static/form.css
  strictdoc/export/html/form_objects/document_grammar_form_object.py
  strictdoc/export/html/form_objects/form_object.py
  strictdoc/export/html/form_objects/grammar_form_object.py
  strictdoc/export/html/form_objects/rows/row_with_grammar_element_form_object.py
  strictdoc/export/html/templates/components/form/field/contenteditable/field_with_human_title.jinja
  strictdoc/export/html/templates/components/form/field/contenteditable/index.jinja
  strictdoc/export/html/templates/components/form/field/file/index.jinja
  strictdoc/export/html/templates/components/form/field/text/index.jinja
  strictdoc/export/html/templates/components/form/row/index.jinja
  strictdoc/export/html/templates/components/form/row/row_uid_with_reset/frame.jinja
  strictdoc/export/html/templates/components/form/row/row_with_comment.jinja
  strictdoc/export/html/templates/components/form/row/row_with_relation.jinja
  strictdoc/export/html/templates/components/form/row/row_with_text_field.jinja
  strictdoc/export/html/templates/components/grammar_form/index.jinja
  strictdoc/export/html/templates/components/grammar_form/row_with_grammar_element/index.jinja
  strictdoc/export/html/templates/components/grammar_form/row_with_new_grammar_element/index.jinja
  strictdoc/export/html/templates/components/grammar_form_element/index.jinja
  strictdoc/export/html/templates/components/grammar_form_element/row_with_custom_field/index.jinja
  strictdoc/export/html/templates/components/grammar_form_element/row_with_relation/index.jinja
  strictdoc/export/html/templates/components/grammar_form_element/row_with_reserved_field/index.jinja
  strictdoc/server/error_object.py
  tests/end2end/helpers/screens/document/form_edit_grammar.py
  tests/integration/expect_exit.py
  tests/integration/html_markup_validator.py
Labels: Core roadmap

#1690 Bump version to 0.0.49a7
  strictdoc/__init__.py
Labels: Second roadmap

#1695 backend/sdoc: resolve relative paths to full paths when importing fragments
  strictdoc/backend/sdoc/free_text_reader.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/reader.py
  tasks.py
  tests/end2end/screens/document/_cross_cutting/fragments/view_section_fragment_basic/__init__.py
  tests/end2end/screens/document/_cross_cutting/fragments/view_section_fragment_basic/expected_output/.dummy.txt
  tests/end2end/screens/document/_cross_cutting/fragments/view_section_fragment_basic/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/fragments/view_section_fragment_basic/input/fragment.sdoc.fgt
  tests/end2end/screens/document/_cross_cutting/fragments/view_section_fragment_basic/test_case.py
Labels: Second roadmap

#1696 backend/sdoc: rework the parsing algorithm for fragments
  strictdoc/backend/sdoc/include_reader.py
  strictdoc/backend/sdoc/pickle_cache.py
  strictdoc/backend/sdoc/post_processing/sdoc_fragment_post_processor.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/reader.py
  tests/integration/features/document_fragments/04_nested_fragments/input.sdoc
  tests/integration/features/document_fragments/04_nested_fragments/input.ssec
  tests/integration/features/document_fragments/04_nested_fragments/input.ssec_nested
  tests/integration/features/document_fragments/04_nested_fragments/test.itest
  tests/integration/features/document_fragments/05_nested_fragments_extra_nesting/input.sdoc
  tests/integration/features/document_fragments/05_nested_fragments_extra_nesting/input.ssec
  tests/integration/features/document_fragments/05_nested_fragments_extra_nesting/input.ssec_nested
  tests/integration/features/document_fragments/05_nested_fragments_extra_nesting/test.itest
Labels: Core roadmap

#1697 backend/sdoc: writing fragments back to files
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/fragment_from_file.py
  strictdoc/backend/sdoc/post_processing/sdoc_fragment_post_processor.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/actions/passthrough_action.py
  strictdoc/core/document_iterator.py
  strictdoc/core/traceability_index.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/_cross_cutting/fragments/read_fragment_section_fragment_basic/__init__.py
  tests/end2end/screens/document/_cross_cutting/fragments/read_fragment_section_fragment_basic/expected_output/.dummy.txt
  tests/end2end/screens/document/_cross_cutting/fragments/read_fragment_section_fragment_basic/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/fragments/read_fragment_section_fragment_basic/input/fragment.sdoc.fgt
  tests/end2end/screens/document/_cross_cutting/fragments/read_fragment_section_fragment_basic/test_case.py
  tests/end2end/screens/document/_cross_cutting/fragments/update_fragment_section_nominal_fields_editing/__init__.py
  tests/end2end/screens/document/_cross_cutting/fragments/update_fragment_section_nominal_fields_editing/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/fragments/update_fragment_section_nominal_fields_editing/expected_output/fragment.sfra
  tests/end2end/screens/document/_cross_cutting/fragments/update_fragment_section_nominal_fields_editing/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/fragments/update_fragment_section_nominal_fields_editing/input/fragment.sfra
  tests/end2end/screens/document/_cross_cutting/fragments/update_fragment_section_nominal_fields_editing/test_case.py
  tests/integration/commands/bypass/50_nested_fragments/input.sdoc
  tests/integration/commands/bypass/50_nested_fragments/nested.sfra
  tests/integration/commands/bypass/50_nested_fragments/sub_nested.sfra
  tests/integration/commands/bypass/50_nested_fragments/test.itest
  tests/unit/strictdoc/backend/sdoc/test_dsl_fragments.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_includes.py
Labels: Core roadmap

#1699 backend/sdoc: writing fragments back to files
  strictdoc/server/routers/main_router.py
Labels: Core roadmap

#1700 Bump version to 0.0.49
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/__init__.py
Labels: Core roadmap

#1702 html2pdf: fix the issue of running within virtual environments
  docs/strictdoc_01_user_guide.sdoc
  pyproject.toml
  strictdoc/__init__.py
  strictdoc/export/html2pdf/pdf_print_driver.py
Labels: Core roadmap

#1704 backend/sdoc: remove last occurrences of Fragment, document the change
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_04_release_notes.sdoc
  docs/strictdoc_20_L1_Open_Requirements_Tool.sdoc
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/models/constants.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/document_from_file.py
  strictdoc/backend/sdoc/models/fragment.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/document_iterator.py
  strictdoc/core/traceability_index_builder.py
Labels: Core roadmap

#1708 UI: Diff screen: do not build source file traceability when doing history
  strictdoc/core/traceability_index_builder.py
  strictdoc/git/change_generator.py
Labels: Bug, Core roadmap

#1710 docs: FAQ: resources: FOSDEM 2024
  docs/strictdoc_02_faq.sdoc
Labels: Documentation, Core roadmap

#1713 Bump version to 0.0.50
  docs/sphinx/source/DO178_requirements.rst
  docs/sphinx/source/Zephyr_requirements.rst
  docs/sphinx/source/_assets/StrictDoc_Roadmap.drawio.png
  docs/sphinx/source/_assets/StrictDoc_Roadmap.drawio.svg
  docs/sphinx/source/strictdoc_01_user_guide.rst
  docs/sphinx/source/strictdoc_02_faq.rst
  docs/sphinx/source/strictdoc_04_release_notes.rst
  docs/sphinx/source/strictdoc_20_L1_Open_Requirements_Tool.rst
  docs/sphinx/source/strictdoc_21_L2_StrictDoc_Requirements.rst
  docs/sphinx/source/strictdoc_28_Backlog.rst
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/__init__.py
Labels: Core roadmap

#1714 docs: regenerate Read the Docs
  docs/sphinx/source/_assets/StrictDoc_Architecture.drawio
  docs/sphinx/source/_assets/StrictDoc_Roadmap.drawio
  docs/sphinx/source/strictdoc_04_release_notes.rst
Labels: Documentation, Core roadmap

#1716 UI: Search screen: fix the case when finding requirements/sections
  strictdoc/export/html/generators/view_objects/search_screen_view_object.py
  strictdoc/export/html/templates/components/form/search.jinja
  strictdoc/export/html/templates/screens/project_index/project_tree_backup.jinja
  strictdoc/export/html/templates/screens/search/legend.jinja
  tests/end2end/helpers/screens/project_index/screen_project_index.py
  tests/end2end/helpers/screens/search/__init__.py
  tests/end2end/helpers/screens/search/search.py
  tests/end2end/screens/search/view_search_screen/__init__.py
  tests/end2end/screens/search/view_search_screen/input.sdoc
  tests/end2end/screens/search/view_search_screen/strictdoc.toml
  tests/end2end/screens/search/view_search_screen/test_case.py
Labels: Bug, Core roadmap

#1717 Bump version to 0.0.51
  docs/sphinx/source/strictdoc_04_release_notes.rst
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/__init__.py
Labels: Core roadmap

#1718 Regenerate CHANGELOG
  CHANGELOG.md
Labels: Documentation, Second roadmap

#1726 docs: regenerate Read the Docs
  docs/sphinx/source/strictdoc_01_user_guide.rst
  docs/strictdoc_01_user_guide.sdoc
Labels: Documentation, Second roadmap

#1727 export/html: Display the node type (requirement and custom) in the document view
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/export/html/_static/node.css
  strictdoc/export/html/templates/components/node/index.jinja
Labels: UI/UX, Core roadmap

#1730 export/html: introduce "Website" layout folder
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/models/document_config.py
  strictdoc/export/html/generators/view_objects/document_screen_view_object.py
  strictdoc/export/html/html_generator.py
  strictdoc/export/html/templates/website/document/index.jinja
  tests/integration/html_markup_validator.py
  tests/unit/helpers/test_document_builder.py
Labels: Core roadmap

#1732 backend/sdoc: including Grammars from grammar files *.sgra
  .coveragerc
  strictdoc/backend/sdoc/error_handling.py
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/grammar/grammar_builder.py
  strictdoc/backend/sdoc/grammar/grammar_grammar.py
  strictdoc/backend/sdoc/grammar/type_system.py
  strictdoc/backend/sdoc/grammar_reader.py
  strictdoc/backend/sdoc/models/constants.py
  strictdoc/backend/sdoc/models/document_config.py
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/models/document_view.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/reader.py
  strictdoc/backend/sdoc/validations/requirement.py
  strictdoc/backend/sdoc/validations/sdoc_validator.py
  strictdoc/core/document_finder.py
  strictdoc/core/document_tree.py
  strictdoc/core/file_tree.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/export/html/templates/screens/document/_shared/project_tree.jinja
  strictdoc/export/html/templates/screens/project_index/project_tree_folder.jinja
  tests/integration/commands/export/html/child_links/02_child_link_not_registered_relation/test.itest
  tests/integration/features/document_grammar/_grammar_from_file/01_basic_grammar_from_file/grammar.sgra
  tests/integration/features/document_grammar/_grammar_from_file/01_basic_grammar_from_file/input.sdoc
  tests/integration/features/document_grammar/_grammar_from_file/01_basic_grammar_from_file/test.itest
  tests/integration/features/document_grammar/_grammar_from_file/_validations/01_grammar_file_not_found/input.sdoc
  tests/integration/features/document_grammar/_grammar_from_file/_validations/01_grammar_file_not_found/test.itest
  tests/integration/features/document_grammar/type_system/multiple_single_choice/validation/01_invalid_value/test.itest
  tests/integration/features/document_grammar/type_system/multiple_single_choice/validation/02_valid_value_but_no_whitespace/test.itest
  tests/integration/features/document_grammar/type_system/single_choice/validation/01_invalid_value/test.itest
  tests/integration/features/document_grammar/type_system/tag/validation/01_invalid_value/test.itest
  tests/integration/features/document_grammar/validation/01_unknown_requirement_type/test.itest
  tests/integration/features/document_grammar/validation/02_invalid_field/test.itest
  tests/integration/features/document_grammar/validation/03_valid_field_but_incorrect_order/test.itest
  tests/integration/features/document_grammar/validation/04_missing_required_grammar_field/test.itest
  tests/integration/features/document_grammar/validation/05_unexpected_field_outside_grammar/test.itest
  tests/integration/features/document_grammar/validation/06_gef_reference_type_not_allowed/test.itest
  tests/integration/features/document_grammar/validation/07_grammar_missing_reserved_statement_field/test.itest
  tests/integration/features/views/_validations/01_view_references_nonexisting_grammar_element/test.itest
  tests/integration/features/views/_validations/03_view_references_nonexisting_field/test.itest
  tests/integration/features/views/_validations/04_default_view_doesnt_exist/test.itest
  tests/integration/features/views/_validations/05_default_view_with_no_views_in_document/test.itest
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_relations_validation.py
  tests/unit/strictdoc/backend/sdoc/validations/test_requirement_validations.py
  tests/unit/strictdoc/core/test_traceability_index.py
  tests/unit/strictdoc/core/test_traceability_index_cycles.py
  tests/unit/strictdoc/core/transforms/test_update_requirement.py
Labels: Core roadmap

#1731 backend/sdoc: read/write LAYOUT option
  strictdoc/backend/sdoc/models/document_config.py
  strictdoc/backend/sdoc/writer.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
Labels: Core roadmap

#1734 UI: Edit grammar form: block when a grammar is imported from file
  .gitignore
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_04_release_notes.sdoc
  docs/strictdoc_20_L1_Open_Requirements_Tool.sdoc
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  docs/strictdoc_28_Backlog.sdoc
  docs_extra/DO178_requirements.sdoc
  strictdoc/core/traceability_index_builder.py
  strictdoc/export/html/_static/content.css
  strictdoc/export/html/form_objects/grammar_form_object.py
  strictdoc/export/html/templates/components/grammar_form/index.jinja
  strictdoc/server/routers/main_router.py
  tests/end2end/helpers/screens/document/form_edit_grammar_elements.py
  tests/end2end/screens/document/view_document/_grammar_from_file/view_document_with_grammar_from_file/__init__.py
  tests/end2end/screens/document/view_document/_grammar_from_file/view_document_with_grammar_from_file/document.sdoc
  tests/end2end/screens/document/view_document/_grammar_from_file/view_document_with_grammar_from_file/grammar.sgra
  tests/end2end/screens/document/view_document/_grammar_from_file/view_document_with_grammar_from_file/test_case.py
Labels: Documentation, Core roadmap

#1737 docs: regenerate Read the Docs
  docs/sphinx/source/DO178_requirements.rst
  docs/sphinx/source/strictdoc_01_user_guide.rst
  docs/sphinx/source/strictdoc_04_release_notes.rst
  docs/sphinx/source/strictdoc_20_L1_Open_Requirements_Tool.rst
  docs/sphinx/source/strictdoc_21_L2_StrictDoc_Requirements.rst
  docs/sphinx/source/strictdoc_28_Backlog.rst
Labels: Documentation, Core roadmap

#1738 Bump version to 0.0.52
  docs/sphinx/source/strictdoc_04_release_notes.rst
  docs/sphinx/source/strictdoc_28_Backlog.rst
  docs/strictdoc_04_release_notes.sdoc
  docs/strictdoc_28_Backlog.sdoc
  strictdoc/__init__.py
Labels: Core roadmap

#1739 export/html: collapsible_tree.js: double-click only affects current and child folders
  strictdoc/export/html/_static/collapsible_tree.js
Labels: UI/UX, Second roadmap

#1740 export/json: handle more corner cases: nodes without levels, included documents
  strictdoc/backend/sdoc/models/document_from_file.py
  strictdoc/export/json/json_generator.py
  tests/integration/commands/export/json/02_export_json_with_included_documents/input.sdoc
  tests/integration/commands/export/json/02_export_json_with_included_documents/input_included.sdoc
  tests/integration/commands/export/json/02_export_json_with_included_documents/strictdoc.toml
  tests/integration/commands/export/json/02_export_json_with_included_documents/test.itest
Labels: Core roadmap

#1742 document_iterator: refactor the iteration algorithm
  strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/models/constants.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/document_from_file.py
  strictdoc/backend/sdoc/models/object_factory.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/document_iterator.py
  strictdoc/core/level_counter.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/section.py
  strictdoc/export/json/json_generator.py
  strictdoc/export/spdx/spdx_to_sdoc_converter.py
  strictdoc/server/routers/main_router.py
  tests/integration/scripting_examples/reqif/02_user_provided_example/script.py
  tests/unit/helpers/test_document_builder.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
  tests/unit/strictdoc/backend/sdoc/test_requirement_from_dict.py
  tests/unit/strictdoc/core/test_level_counter.py
  tools/confluence_html_table_import.py
Labels: Core roadmap

#1743 Code climate: improve a grammar form object class name
  strictdoc/core/transforms/update_grammar_element.py
  strictdoc/export/html/form_objects/grammar_element_form_object.py
  strictdoc/server/routers/main_router.py
Labels: Code climate, Second roadmap

#1744 Remove all BibTeX bibliography-related code and pybtex dependency
  developer/pyinstaller_hooks/hook-latexcodec.py
  developer/pyinstaller_hooks/hook-six.py
  pyproject.toml
  strictdoc/backend/excel/export/excel_generator.py
  strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/reqif/p11_polarion/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/grammar/grammar_grammar.py
  strictdoc/backend/sdoc/grammar/type_system.py
  strictdoc/backend/sdoc/models/constants.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/document_bibliography.py
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/models/object_factory.py
  strictdoc/backend/sdoc/models/reference.py
  strictdoc/backend/sdoc/models/type_system.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/export/html/templates/screens/document/table/main.jinja
  strictdoc/export/spdx/spdx_to_sdoc_converter.py
  strictdoc/server/routers/main_router.py
  tasks.py
  tasks_wine.py
  tests/integration/backend/excel/export/04_custom_grammar_fields_to_export_fields_subset/input.sdoc
  tests/integration/backend/excel/export/05_custom_grammar_fields_to_export_fields_default/input.sdoc
  tests/integration/backend/excel/export/06_custom_grammar_fields_to_export_fields_all/input.sdoc
  tests/integration/backend/excel/export/07_custom_grammar_fields_to_export_fields_all_special/input.sdoc
  tests/integration/deprecations/refs_replaced_with_relations/11_raise_error_if_refs_is_string_in_requirement/input.sdoc
  tests/integration/scripting_examples/reqif/02_user_provided_example/script.py
  tests/unit/helpers/test_document_builder.py
  tests/unit/strictdoc/backend/sdoc/bib-files/ctan_biblatex-examples.bib
  tests/unit/strictdoc/backend/sdoc/bib-files/ctan_bibtex-test_test.bib
  tests/unit/strictdoc/backend/sdoc/models/test_requirement.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_grammars.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_bibtex.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar.py
  tests/unit/strictdoc/backend/sdoc/validations/test_requirement_validations.py
  tools/confluence_html_table_import.py
Labels: Core roadmap

#1745 docs: update requirements (ZEP, data integrity, fix all missing statuses, a few rationales)
  docs/strictdoc_20_L1_Open_Requirements_Tool.sdoc
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
Labels: Documentation, Core roadmap

#1746 export/json: do not export included documents by default
  strictdoc/backend/sdoc/models/document.py
  strictdoc/cli/cli_arg_parser.py
  strictdoc/cli/command_parser_builder.py
  strictdoc/core/actions/export_action.py
  strictdoc/core/project_config.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/export/html/templates/screens/document/_shared/project_tree.jinja
  strictdoc/export/html/templates/screens/project_index/index.jinja
  strictdoc/export/html/templates/screens/project_index/project_tree_file.jinja
  strictdoc/export/json/json_generator.py
  strictdoc/server/routers/main_router.py
  tests/integration/commands/export/json/02_export_json_with_included_documents/test.itest
  tests/integration/commands/export/json/02_export_without_and_with_included_documents/input.sdoc
  tests/integration/commands/export/json/02_export_without_and_with_included_documents/input_included.sdoc
  tests/integration/commands/export/json/02_export_without_and_with_included_documents/strictdoc.toml
  tests/integration/commands/export/json/02_export_without_and_with_included_documents/test.itest
  tests/unit/strictdoc/cli/test_cli_arg_parser.py
Labels: Core roadmap

#1747 docs: document less portable features
  docs/strictdoc_01_user_guide.sdoc
Labels: Documentation, Core roadmap

#1749 export/json: fix and simplify the iteration algorithm one more time
  strictdoc/export/json/json_generator.py
Labels: Core roadmap

#1751 docs: update Roadmap
  docs/_assets/StrictDoc_Architecture.drawio
  docs/_assets/StrictDoc_Roadmap.drawio
  docs/_assets/StrictDoc_Roadmap.drawio.png
  docs/_assets/StrictDoc_Roadmap.drawio.svg
Labels: Documentation, Core roadmap
