Repository strictdoc-project/strictdoc, pull requests merged in 2024-06, with the labels that each got.

#1835 Feature: LINK to requirements and custom nodes (static export only for now)
  docs/strictdoc_01_user_guide.sdoc
  strictdoc/core/traceability_index.py
  strictdoc/core/transforms/section.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/html/templates/components/anchor/index.jinja
  strictdoc/export/html/templates/rst/anchor.jinja
  strictdoc/export/rst/writer.py
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/_cross_cutting/anchors/document/update_document_add_requirement_and_create_section_with_link/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/anchors/document/update_document_add_requirement_and_create_section_with_link/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/anchors/document/update_document_add_requirement_and_create_section_with_link/test_update_document_add_requirement_and_create_section_with_link.py
  tests/integration/commands/export/html/markup/04_referencing_a_section_with_LINK_node/input.sdoc
  tests/integration/commands/export/html/markup/04_referencing_a_section_with_LINK_node/nodes.sdoc
  tests/integration/commands/export/html/markup/04_referencing_a_section_with_LINK_node/test.itest
  tests/integration/commands/export/rst/41_link_to_node/expected/input.rst
  tests/integration/commands/export/rst/41_link_to_node/input.sdoc
  tests/integration/commands/export/rst/41_link_to_node/test.itest
Labels: Core roadmap

#1842 Code climate: Introduce THIS_TEST_FOLDER to increase the portability of most itests
  tests/integration/commands/export/02_minimal_document_with_freetext/test.itest
  tests/integration/lit.cfg
Labels: Code climate

#1843 Feature: [LINK] from all fields of Requirement or other nodes
  strictdoc/backend/excel/export/excel_generator.py
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/reqif/p02_simple/sdoc_to_reqif_converter.py
  strictdoc/backend/sdoc/error_handling.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/validations/sdoc_validator.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/query_engine/query_object.py
  strictdoc/core/traceability_index.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/generators/project_statistics.py
  strictdoc/export/html/generators/view_objects/document_screen_view_object.py
  strictdoc/export/html/generators/view_objects/search_screen_view_object.py
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/html/templates/components/requirement/comments/index.jinja
  strictdoc/export/html/templates/components/requirement/meta/index.jinja
  strictdoc/export/html/templates/components/requirement/multiline/index.jinja
  strictdoc/export/html/templates/components/requirement/rationale/index.jinja
  strictdoc/export/html/templates/components/requirement/statement/index.jinja
  strictdoc/export/html/templates/screens/document/table/main.jinja
  strictdoc/export/json/json_generator.py
  strictdoc/export/rst/templates/requirement.jinja.rst
  strictdoc/git/project_diff_analyzer.py
  strictdoc/server/routers/main_router.py
  tests/integration/commands/export/html/markup/10_node_LINK_references_a_section/input.sdoc
  tests/integration/commands/export/html/markup/10_node_LINK_references_a_section/section.sdoc
  tests/integration/commands/export/html/markup/10_node_LINK_references_a_section/test.itest
  tests/integration/features/document_grammar/30_grammar_without_statement_but_with_description/input.sdoc
  tests/integration/features/document_grammar/30_grammar_without_statement_but_with_description/test.itest
  tests/unit/strictdoc/backend/sdoc/models/test_requirement.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_grammars.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
  tests/unit/tools/test_confluence_html_table_import.py
Labels: Core roadmap

#1844 export/html, LINK: referenced node shows an anchor link if referenced with [LINK]
  strictdoc/backend/sdoc/models/anchor.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/core/graph_database.py
  strictdoc/core/traceability_index.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/core/transforms/section.py
  strictdoc/export/html/_static/controllers/anchor_controller.js
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/html/templates/components/anchor/index.jinja
  strictdoc/export/html/templates/rst/anchor.jinja
  strictdoc/export/rst/writer.py
  tests/end2end/screens/document/_cross_cutting/anchors/section/create_section_with_anchor_and_section_with_link/test_case.py
  tests/end2end/screens/document/_cross_cutting/anchors/section/create_section_with_uid_and_section_with_link/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/anchors/section/create_section_with_uid_and_section_with_link/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/anchors/section/create_section_with_uid_and_section_with_link/test_case.py
  tests/integration/commands/export/html/markup/10_node_LINK_references_a_section/test.itest
Labels: Core roadmap

#1845 UI: requirement_form_object: improve handling of multiline field boundary
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/export/html/form_objects/requirement_form_object.py
Labels: Second roadmap

#1847 docs: release notes for 0.0.56
  docs/_assets/StrictDoc_Roadmap.drawio.png
  docs/_assets/StrictDoc_Roadmap.drawio.svg
  docs/sphinx/source/_assets/StrictDoc_Roadmap.drawio.png
  docs/sphinx/source/_assets/StrictDoc_Roadmap.drawio.svg
  docs/sphinx/source/strictdoc_04_release_notes.rst
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/__init__.py
Labels: Core roadmap

#1849 UI: Delete section/node: Add validations to the confirmation window
  strictdoc/core/traceability_index.py
  strictdoc/core/transforms/delete_requirement.py
  strictdoc/core/transforms/delete_section.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/core/transforms/validation_error.py
  strictdoc/export/html/_static/element.css
  strictdoc/export/html/templates/actions/document/delete_requirement/stream_confirm_delete_requirement.jinja
  strictdoc/export/html/templates/actions/document/delete_section/stream_confirm_delete_section.jinja
  strictdoc/export/html/templates/components/confirm/index.jinja
  strictdoc/server/routers/main_router.py
  tests/end2end/helpers/components/node/node.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_remove_section_that_has_incoming_links/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_remove_section_that_has_incoming_links/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_remove_section_that_has_incoming_links/test_document_remove_section_that_has_incoming_links.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_validations/remove_node_that_has_incoming_links/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_validations/remove_node_that_has_incoming_links/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_validations/remove_node_that_has_incoming_links/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_validations/remove_section_that_has_incoming_links/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_validations/remove_section_that_has_incoming_links/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_validations/remove_section_that_has_incoming_links/test_case.py
Labels: Core roadmap

#1851 backend/reqif: when --reqif-multiline-is-xhtml, generate FREETEXT spec type attribute as XHTML
  strictdoc/__init__.py
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  tests/integration/backend/reqif/profiles/p01_sdoc/end_to_end/--reqif-multiline-is-xhtml/01_cli_option/test.itest
  tests/integration/backend/reqif/profiles/p01_sdoc/end_to_end/--reqif-multiline-is-xhtml/02_toml_option/test.itest
Labels: Second roadmap

#1852 UI: Create node: parse and validate LINK/ANCHOR
  strictdoc/backend/sdoc/free_text_reader.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/export/html/templates/actions/document/delete_requirement/stream_confirm_delete_requirement.jinja
  strictdoc/export/html/templates/actions/document/delete_section/stream_confirm_delete_section.jinja
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/create_node_with_LINK/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/create_node_with_LINK/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/create_node_with_LINK/test_case.py
Labels: Core roadmap

#1854 UI: Create node: parse, validate, and render LINK/ANCHOR
  strictdoc/core/traceability_index_builder.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/validation_error.py
  strictdoc/helpers/string.py
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_create_anchor_already_exists_in_tree/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_create_anchor_already_exists_in_tree/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_create_anchor_already_exists_in_tree/test_document_create_anchor_already_exists_in_tree.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_create_anchor_broken_rst/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_create_anchor_broken_rst/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_create_anchor_broken_rst/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_create_duplicated_anchor/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_create_duplicated_anchor/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/document/_validations_document/DEPRECATED_document_create_duplicated_anchor/test_document_create_duplicated_anchor.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_ANCHOR_already_exists/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_ANCHOR_already_exists/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_ANCHOR_already_exists/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_ANCHOR_with_broken_rst/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_ANCHOR_with_broken_rst/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_ANCHOR_with_broken_rst/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_LINK_does_not_exist/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_LINK_does_not_exist/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_LINK_does_not_exist/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_duplicate_ANCHOR/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_duplicate_ANCHOR/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/_validations/create_node_must_validate_duplicate_ANCHOR/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/create_node_with_ANCHOR/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/create_node_with_ANCHOR/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/create_node_with_ANCHOR/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/create_node_with_LINK/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/create_node_with_LINK/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_create/create_node_with_LINK/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_remove/_validations/remove_node_that_has_incoming_links/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_remove/_validations/remove_node_that_has_incoming_links/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_remove/_validations/remove_node_that_has_incoming_links/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_remove/_validations/remove_section_that_has_incoming_links/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_remove/_validations/remove_section_that_has_incoming_links/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_remove/_validations/remove_section_that_has_incoming_links/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/DEPRECATED_create_section_with_anchor_and_section_with_link/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/DEPRECATED_create_section_with_anchor_and_section_with_link/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/DEPRECATED_create_section_with_anchor_and_section_with_link/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/DEPRECATED_create_section_with_uid_and_section_with_link/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/DEPRECATED_create_section_with_uid_and_section_with_link/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/DEPRECATED_create_section_with_uid_and_section_with_link/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/DEPRECATED_update_section_add_anchor_in_section_and_link_in_another_section/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/DEPRECATED_update_section_add_anchor_in_section_and_link_in_another_section/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/DEPRECATED_update_section_add_anchor_in_section_and_link_in_another_section/test_update_section_add_anchor_in_section_and_link_in_another_section.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/_validations_section/DEPRECATED_create_section_must_not_add_anchor_broken_rst/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/_validations_section/DEPRECATED_create_section_must_not_add_anchor_broken_rst/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/_validations_section/DEPRECATED_create_section_must_not_add_anchor_broken_rst/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/_validations_section/DEPRECATED_create_section_must_not_add_link_to_nonexisting_node/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/_validations_section/DEPRECATED_create_section_must_not_add_link_to_nonexisting_node/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/section/_validations_section/DEPRECATED_create_section_must_not_add_link_to_nonexisting_node/test_case.py
Labels: Core roadmap

#1859 UI: Delete node: incoming links to anchors validation
  strictdoc/backend/sdoc/models/node.py
  strictdoc/core/traceability_index.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/core/transforms/delete_requirement.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_delete/_validations/delete_node_that_has_incoming_links/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_delete/_validations/delete_node_that_has_incoming_links/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_delete/_validations/delete_node_that_has_incoming_links/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_delete/_validations/delete_node_with_anchor_that_has_incoming_links/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_delete/_validations/delete_node_with_anchor_that_has_incoming_links/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_delete/_validations/delete_node_with_anchor_that_has_incoming_links/test_case.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_delete/_validations/delete_section_that_has_incoming_links/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_delete/_validations/delete_section_that_has_incoming_links/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_delete/_validations/delete_section_that_has_incoming_links/test_case.py
  tests/end2end/screens/document/_cross_cutting/text_nodes/update_text_node_add_uid/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/text_nodes/update_text_node_add_uid/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/text_nodes/update_text_node_add_uid/test_case.py
  tests/end2end/screens/document/_cross_cutting/text_nodes/update_text_node_update_uid/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/text_nodes/update_text_node_update_uid/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/text_nodes/update_text_node_update_uid/test_case.py
Labels: Core roadmap

#1867 UI: Diff screen: Ensure escaping of requirement fields
  strictdoc/backend/sdoc/models/node.py
  strictdoc/export/html/templates/screens/git/fields/document_fields.jinja
  strictdoc/export/html/templates/screens/git/fields/requirement_fields.jinja
  strictdoc/export/html/templates/screens/git/fields/section_fields.jinja
Labels: Core roadmap

#1868 backend/sdoc: Document: remove .free_texts
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/export/json/json_generator.py
  strictdoc/export/rst/writer.py
  strictdoc/git/change.py
  strictdoc/git/project_diff_analyzer.py
  tests/end2end/__init__.py
  tests/end2end/project_index/import_document_from_reqif/import_document_from_reqif_tree_of_two_documents/expected_output/Document_1.sdoc
  tests/end2end/project_index/import_document_from_reqif/import_document_from_reqif_tree_of_two_documents/expected_output/Document_2.sdoc
  tests/end2end/project_index/import_document_from_reqif/import_document_from_reqif_tree_of_two_documents/sample.reqif
  tests/end2end/project_index/import_document_from_reqif/import_document_from_reqif_tree_of_two_documents/test_case.py
  tests/integration/backend/reqif/profiles/p01_sdoc/end_to_end/--reqif-multiline-is-xhtml/01_cli_option/test.itest
  tests/integration/backend/reqif/profiles/p01_sdoc/end_to_end/--reqif-multiline-is-xhtml/02_toml_option/test.itest
  tests/integration/features/diff/80__documents__changed_free_text/test.itest
Labels: Core roadmap

#1869 Node machine identifiers (MID): improve uniqueness validation message
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/core/traceability_index_builder.py
  tests/integration/error_handling/graph_consistency/20_document_mid_is_not_unique/test.itest
  tests/integration/error_handling/graph_consistency/21_section_mid_is_not_unique/test.itest
  tests/integration/error_handling/graph_consistency/22_requirement_mid_is_not_unique/test.itest
  tests/integration/features/machine_identifiers_MID/_validations/01_document_mid_must_be_unique/input.sdoc
  tests/integration/features/machine_identifiers_MID/_validations/01_document_mid_must_be_unique/input2.sdoc
  tests/integration/features/machine_identifiers_MID/_validations/01_document_mid_must_be_unique/test.itest
  tests/integration/features/machine_identifiers_MID/_validations/02_section_mid_must_be_unique/input.sdoc
  tests/integration/features/machine_identifiers_MID/_validations/02_section_mid_must_be_unique/input2.sdoc
  tests/integration/features/machine_identifiers_MID/_validations/02_section_mid_must_be_unique/test.itest
  tests/integration/features/machine_identifiers_MID/_validations/03_requirement_mid_must_be_unique/input.sdoc
  tests/integration/features/machine_identifiers_MID/_validations/03_requirement_mid_must_be_unique/input2.sdoc
  tests/integration/features/machine_identifiers_MID/_validations/03_requirement_mid_must_be_unique/test.itest
Labels: Second roadmap

#1870 Bump version to 0.0.57a2
  strictdoc/__init__.py
Labels: Second roadmap

#1873 Remove Graphviz and DocumentDotGenerator
  .github/workflows/ci-linux-ubuntu-latest.yml
  .github/workflows/ci-mac.yml
  .github/workflows/periodic-integration-test.yml
  .github/workflows/periodic-release-test.yml
  docs/strictdoc_03_development_plan.sdoc
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  pyproject.toml
  strictdoc/cli/command_parser_builder.py
  strictdoc/core/actions/export_action.py
  strictdoc/core/environment.py
  strictdoc/export/dot/document_dot_generator.py
  strictdoc/export/dot/dot_templates.py
  strictdoc/export/dot/templates/profile1/document.dot
  strictdoc/export/dot/templates/profile1/folder.dot
  strictdoc/export/dot/templates/profile1/legend.dot
  strictdoc/export/dot/templates/profile1/requirement.dot
  strictdoc/export/dot/templates/profile1/section.dot
  strictdoc/export/dot/templates/profile1/top_level.dot
  strictdoc/export/dot/templates/profile2/document.dot
  strictdoc/export/dot/templates/profile2/folder.dot
  strictdoc/export/dot/templates/profile2/requirement.dot
  strictdoc/export/dot/templates/profile2/section.dot
  strictdoc/export/dot/templates/profile2/top_level.dot
  tasks.py
  tests/integration/commands/export/dot/01_minimal_document/input.sdoc
  tests/integration/commands/export/dot/01_minimal_document/test.itest
  tests/integration/commands/export/options/--formats/01_incorrect_format/test.itest
Labels: Second roadmap

#1871 UI: Edit grammar element relations form: TEXT node can have no relations
  strictdoc/export/html/form_objects/grammar_element_form_object.py
  tests/end2end/screens/document/edit_document_grammar_element/_relations/update_grammar_text_node_noop_save_preserves_relations/expected_output/document.sdoc
  tests/end2end/screens/document/edit_document_grammar_element/_relations/update_grammar_text_node_noop_save_preserves_relations/input/document.sdoc
  tests/end2end/screens/document/edit_document_grammar_element/_relations/update_grammar_text_node_noop_save_preserves_relations/test_case.py
Labels: Core roadmap

#1872 UI: Ensure that documents with HTML markup get rendered correctly when edited
  strictdoc/backend/sdoc/models/document_config.py
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/update_requirement/update_requirement_when_HTML_markup/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/update_requirement_when_HTML_markup/input/document.sdoc
  tests/end2end/screens/document/update_requirement/update_requirement_when_HTML_markup/test_case.py
Labels: Core roadmap

#1874 tasks: remove pylint and flake8, create aliases for most common tasks
  .pylint.ini
  tasks.py
Labels: Code climate, Second roadmap

#1877 UI: Node form validation: allow empty SingleChoice fields when REQUIRED is False
  strictdoc/__init__.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  tests/end2end/screens/document/update_requirement/update_requirement_saves_empty_SingleChoice_value/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/update_requirement_saves_empty_SingleChoice_value/input/document.sdoc
  tests/end2end/screens/document/update_requirement/update_requirement_saves_empty_SingleChoice_value/test_case.py
Labels: Core roadmap

#1879 UI: Do not auto-generate UID for TEXT nodes for now
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/templates/screens/document/document/frame_requirement_form.jinja
  strictdoc/server/routers/main_router.py
  tests/end2end/helpers/components/node/add_node_menu.py
  tests/end2end/screens/document/_cross_cutting/text_nodes/create_text_node_in_top_level_document/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/text_nodes/create_text_node_in_top_level_document/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/text_nodes/create_text_node_in_top_level_document/test_case.py
Labels: Core roadmap

#1880 docs: update release notes
  docs/strictdoc_04_release_notes.sdoc
Labels: Documentation

#1881 docs: User Guide: implement FREETEXT-TEXT changes
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_04_release_notes.sdoc
Labels: Documentation, Core roadmap

#1882 cli: passthrough: --free-text-to-text option to migrate FREETEXT->TEXT
  strictdoc/backend/sdoc/writer.py
  strictdoc/cli/cli_arg_parser.py
  strictdoc/cli/command_parser_builder.py
  strictdoc/core/actions/passthrough_action.py
  strictdoc/core/project_config.py
  tests/integration/commands/bypass/60_FREETEXT-TEXT/expected/input1.sdoc
  tests/integration/commands/bypass/60_FREETEXT-TEXT/expected/input2.sdoc
  tests/integration/commands/bypass/60_FREETEXT-TEXT/input1.sdoc
  tests/integration/commands/bypass/60_FREETEXT-TEXT/input2.sdoc
  tests/integration/commands/bypass/60_FREETEXT-TEXT/test.itest
  tests/unit/strictdoc/cli/test_cli_arg_parser.py
Labels: Core roadmap

#1883 docs: User Guide: describe FREETEXT-TEXT migration path
  docs/_assets/StrictDoc_Workspace-FREETEXT-TEXT.drawio.png
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_04_release_notes.sdoc
Labels: Documentation, Core roadmap

#1886 backend/sdoc: writer: --free-text-to-text for SECTIONs
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/writer.py
  tests/end2end/__init__.py
  tests/end2end/project_index/import_document_from_reqif/import_document_from_reqif_tree_of_two_documents/expected_output/Document_1.sdoc
  tests/end2end/project_index/import_document_from_reqif/import_document_from_reqif_tree_of_two_documents/expected_output/Document_2.sdoc
  tests/integration/commands/bypass/60_FREETEXT-TEXT/expected/input1.sdoc
  tests/integration/commands/bypass/60_FREETEXT-TEXT/expected/input2.sdoc
  tests/integration/commands/bypass/60_FREETEXT-TEXT/input1.sdoc
  tests/integration/commands/bypass/60_FREETEXT-TEXT/input2.sdoc
Labels: Core roadmap

#1893 UI: TRM: Exclude text nodes from the list
  strictdoc/export/html/templates/screens/traceability_matrix/main.jinja
Labels: Core roadmap

#1899 backend/sdoc: relax the validation of UID when running Manage/AutoUID
  strictdoc/__init__.py
  strictdoc/backend/sdoc/validations/sdoc_validator.py
  strictdoc/commands/manage_autouid_command.py
  strictdoc/core/traceability_index_builder.py
  tests/end2end/__init__.py
  tests/integration/commands/manage/auto-uid/requirement_uids/09_edge_grammar_UID_required/input.expected.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/09_edge_grammar_UID_required/input.sdoc
  tests/integration/commands/manage/auto-uid/requirement_uids/09_edge_grammar_UID_required/test.itest
  tests/integration/features/document_grammar/validation/03b_valid_field_but_incorrect_order_UID/input.sdoc
  tests/integration/features/document_grammar/validation/03b_valid_field_but_incorrect_order_UID/test.itest
  tests/integration/features/document_grammar/validation/04a_missing_required_grammar_field_node_has_less_fields_than_grammar/input.sdoc
  tests/integration/features/document_grammar/validation/04a_missing_required_grammar_field_node_has_less_fields_than_grammar/test.itest
  tests/integration/features/document_grammar/validation/04b_missing_required_grammar_field/input.sdoc
  tests/integration/features/document_grammar/validation/04b_missing_required_grammar_field/test.itest
Labels: Core roadmap

#1901 Bump version to 0.0.58
  docs/sphinx/source/strictdoc_01_user_guide.rst
  docs/sphinx/source/strictdoc_04_release_notes.rst
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/__init__.py
Labels: Core roadmap
