Repository strictdoc-project/strictdoc, pull requests merged in 2024-07, with the labels that each got.

#1910 views: Support custom views for passthrough
  strictdoc/backend/sdoc/writer.py
  strictdoc/cli/cli_arg_parser.py
  strictdoc/cli/command_parser_builder.py
  strictdoc/commands/manage_autouid_command.py
  strictdoc/core/actions/import_action.py
  strictdoc/core/actions/passthrough_action.py
  strictdoc/core/project_config.py
  strictdoc/export/spdx/spdx_generator.py
  strictdoc/server/routers/main_router.py
  tests/integration/commands/passthrough/--view/01_view_option_is_provided/input.sdoc
  tests/integration/commands/passthrough/--view/01_view_option_is_provided/test.itest
  tests/integration/commands/passthrough/--view/02_if_view_option_is_not_provided_then_default_view/input.sdoc
  tests/integration/commands/passthrough/--view/02_if_view_option_is_not_provided_then_default_view/test.itest
  tests/integration/scripting_examples/reqif/02_user_provided_example/script.py
  tests/unit/conftest.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_document_views.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_free_text.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar_from_file.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_relations.py
  tests/unit/strictdoc/cli/test_cli_arg_parser.py
  tools/confluence_html_table_import.py
Labels: Core roadmap

#1915 export: HTML2PDF: render bundle document
  strictdoc/backend/sdoc/models/anchor.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/cli/cli_arg_parser.py
  strictdoc/cli/command_parser_builder.py
  strictdoc/core/actions/export_action.py
  strictdoc/core/document_meta.py
  strictdoc/core/file_tree.py
  strictdoc/core/project_config.py
  strictdoc/core/traceability_index.py
  strictdoc/export/html/document_type.py
  strictdoc/export/html/generators/view_objects/document_screen_view_object.py
  strictdoc/export/html/html_generator.py
  strictdoc/export/html/renderers/link_renderer.py
  strictdoc/export/html/templates/rst/anchor.jinja
  strictdoc/export/html/templates/screens/document/_shared/viewtype_menu.jinja
  strictdoc/export/html/templates/screens/source_file_view/requirement.jinja
  strictdoc/export/html2pdf/html2pdf.py
  strictdoc/export/html2pdf/html2pdf_generator.py
  strictdoc/server/routers/main_router.py
  tests/integration/features/html2pdf/05_generate_bundle_document/_assets/file.svg
  tests/integration/features/html2pdf/05_generate_bundle_document/input.sdoc
  tests/integration/features/html2pdf/05_generate_bundle_document/nested/_assets/file.svg
  tests/integration/features/html2pdf/05_generate_bundle_document/nested/input2.sdoc
  tests/integration/features/html2pdf/05_generate_bundle_document/nested/subnested/_assets/file.svg
  tests/integration/features/html2pdf/05_generate_bundle_document/nested/subnested/input3.sdoc
  tests/integration/features/html2pdf/05_generate_bundle_document/strictdoc.toml
  tests/integration/features/html2pdf/05_generate_bundle_document/test.itest
  tests/integration/features/html2pdf/05_generate_bundle_document/test_pdf.py
  tests/unit/strictdoc/cli/test_cli_arg_parser.py
Labels: Core roadmap

#1919 Code climate: get_included_document -> get_including_document
  strictdoc/backend/sdoc/models/anchor.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/core/transforms/section.py
  strictdoc/export/html/renderers/link_renderer.py
  strictdoc/export/html/templates/screens/project_index/project_tree_file.jinja
Labels: Second roadmap

#1922 Code climate: fix several issues related to new Ruff checks
  requirements.check.txt
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/models/document_config.py
  strictdoc/core/file_tree.py
  tests/integration/features/file_traceability/16_difference_in_nonrange_links_to_this_and_other_files/file1.py
  tests/integration/scripting_examples/reqif/02_user_provided_example/script.py
Labels: Second roadmap

#1923 Code climate: document_iterator: add SDocAnyNode type hint
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/sdoc/models/any_node.py
  strictdoc/backend/sdoc/models/document_config.py
  strictdoc/core/document_iterator.py
  strictdoc/core/traceability_index_builder.py
  tests/end2end/__init__.py
Labels: Code climate, Second roadmap

#1924 Code climate: remove unused render_free_text()
  strictdoc/export/html/generators/view_objects/document_screen_view_object.py
  strictdoc/export/html/generators/view_objects/search_screen_view_object.py
  strictdoc/export/html/generators/view_objects/source_file_view_object.py
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/html/templates/screens/document/table/main.jinja
Labels: Code climate, Second roadmap

#1926 Code climate: markup_renderer: remove unused code
  strictdoc/export/html/renderers/html_fragment_writer.py
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/html/renderers/text_to_html_writer.py
  strictdoc/export/rst/rst_to_html_fragment_writer.py
Labels: Second roadmap

#1927 Code climate: markup_renderer: fix all mypy issues
  strictdoc/export/html/renderers/markup_renderer.py
Labels: Code climate

#1921 Use Jinja2 autoescaping
  docs/strictdoc_25_design.sdoc
  strictdoc/backend/sdoc/models/free_text.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/html/form_objects/form_object.py
  strictdoc/export/html/form_objects/grammar_element_form_object.py
  strictdoc/export/html/form_objects/grammar_form_object.py
  strictdoc/export/html/form_objects/included_document_form_object.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/form_objects/rows/row_with_grammar_element_form_object.py
  strictdoc/export/html/form_objects/section_form_object.py
  strictdoc/export/html/generators/source_file_coverage.py
  strictdoc/export/html/generators/source_file_view_generator.py
  strictdoc/export/html/generators/view_objects/diff_screen_results_view_object.py
  strictdoc/export/html/generators/view_objects/diff_screen_view_object.py
  strictdoc/export/html/generators/view_objects/document_screen_view_object.py
  strictdoc/export/html/generators/view_objects/nestor_view_object.py
  strictdoc/export/html/generators/view_objects/project_statistics_view_object.py
  strictdoc/export/html/generators/view_objects/project_tree_view_object.py
  strictdoc/export/html/generators/view_objects/search_screen_view_object.py
  strictdoc/export/html/generators/view_objects/source_file_view_object.py
  strictdoc/export/html/generators/view_objects/traceability_matrix_view_object.py
  strictdoc/export/html/html_templates.py
  strictdoc/export/html/renderers/html_fragment_writer.py
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/html/renderers/text_to_html_writer.py
  strictdoc/export/html/templates/components/form/row/row_uid_with_reset/example.jinja.html
  strictdoc/export/html/templates/components/form/row/row_uid_with_reset/frame.jinja
  strictdoc/export/html/templates/components/form/row/row_with_comment.jinja
  strictdoc/export/html/templates/components/form/row/row_with_text_field.jinja
  strictdoc/export/html/templates/components/node_field/section_h/index.jinja
  strictdoc/export/html/templates/components/node_field/section_title/index.jinja
  strictdoc/export/html/templates/components/node_field/title/index.jinja
  strictdoc/export/html/templates/screens/document/document/frame_requirement_form.jinja
  strictdoc/export/html/templates/screens/document/document/frame_section_form.jinja
  strictdoc/export/html/templates/screens/git/fields/requirement_fields.jinja
  strictdoc/export/html/templates/screens/source_file_view/index.jinja
  strictdoc/export/rst/rst_to_html_fragment_writer.py
  strictdoc/server/helpers/turbo.py
  strictdoc/server/routers/main_router.py
  tests/end2end/project_index/import_document_from_reqif/UC55_G1_validations/UC55_G1_T01_not_a_reqif_format/test_UC55_G1_T01_not_a_reqif_file.py
  tests/integration/options/options_per_document/MARKUP/02_options_markup_is_text/test.itest
  tests/unit/strictdoc/export/html/renderers/test_text_to_html_fragment_writer.py
Labels: Second roadmap

#1931 Bump version to 0.0.59a1
  strictdoc/__init__.py
Labels: Second roadmap
