Repository strictdoc-project/strictdoc, pull requests merged in 2024-02, with the labels that each got.

#1632 Bump version to 0.0.49a3
  strictdoc/__init__.py
Labels: Second roadmap

#1638 export/html: implement --view option
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/document_view.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/cli/cli_arg_parser.py
  strictdoc/cli/command_parser_builder.py
  strictdoc/core/project_config.py
  strictdoc/export/html/generators/document.py
  strictdoc/export/html/generators/document_deep_trace.py
  strictdoc/export/html/generators/document_pdf.py
  strictdoc/export/html/generators/document_trace.py
  strictdoc/export/html/templates/components/requirement/comments/index.jinja
  strictdoc/export/html/templates/components/requirement/meta/index.jinja
  strictdoc/export/html/templates/components/requirement/multiline/index.jinja
  strictdoc/export/html/templates/components/requirement/rationale/index.jinja
  strictdoc/export/html/templates/components/requirement/statement/index.jinja
  strictdoc/server/routers/main_router.py
  tests/integration/commands/export/options/--view/01_view_option_is_provided/input.sdoc
  tests/integration/commands/export/options/--view/01_view_option_is_provided/test.itest
  tests/integration/commands/export/options/--view/02_if_view_option_is_not_provided_then_default_view/input.sdoc
  tests/integration/commands/export/options/--view/02_if_view_option_is_not_provided_then_default_view/test.itest
  tests/unit/strictdoc/cli/test_cli_arg_parser.py
Labels: Core roadmap

#1637 export/html2pdf: improved printing of tables (Firefox edge case)
  strictdoc/export/html/_static/html2pdf/bundle.js
  strictdoc/export/html/templates/screens/document/pdf/index.jinja
Labels: Core roadmap

#1642 export/html2pdf: customize webdriver cache manager to allow offline use
  strictdoc/export/html2pdf/html2pdf.py
  tasks.py
  tests/integration/features/html2pdf/01_empty_document/test.itest
  tests/integration/features/html2pdf/02_three_top_level_requirements/test.itest
  tests/integration/features/html2pdf/03_three_documents_with_assets/test.itest
  tests/integration/lit.cfg
Labels: Core roadmap

#1643 export/excel: allow generating Excel files for inter-document relations
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/backend/excel/export/excel_generator.py
  tests/integration/backend/excel/export/20_excel_export_multiple_docs/expected/input1.xlsx
  tests/integration/backend/excel/export/20_excel_export_multiple_docs/expected/input2.xlsx
  tests/integration/backend/excel/export/20_excel_export_multiple_docs/input1.sdoc
  tests/integration/backend/excel/export/20_excel_export_multiple_docs/input2.sdoc
  tests/integration/backend/excel/export/20_excel_export_multiple_docs/test.itest
Labels: Second roadmap

#1644 export/excel: link Excel export requirement to source files
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  strictdoc/__init__.py
Labels: Documentation, Second roadmap

#1645 server: main_router: treat everything "not .html" as assets
  strictdoc/server/routers/main_router.py
Labels: Second roadmap

#1646 tests/end2end: test opening a hyperlink to an CSV asset
  strictdoc/__init__.py
  tests/end2end/screens/document/_cross_cutting/downloading_assets/download_pdf_asset/__init__.py
  tests/end2end/screens/document/_cross_cutting/downloading_assets/download_pdf_asset/_assets/foo.csv
  tests/end2end/screens/document/_cross_cutting/downloading_assets/download_pdf_asset/document.sdoc
  tests/end2end/screens/document/_cross_cutting/downloading_assets/download_pdf_asset/test_case.py
Labels: SQA, Second roadmap

#1647 Regenerate CHANGELOG
  CHANGELOG.md
Labels: Documentation, Second roadmap

#1650 Refactoring: Node -> SDocObject
  strictdoc/backend/sdoc/models/fragment.py
  strictdoc/backend/sdoc/models/fragment_from_file.py
  strictdoc/backend/sdoc/models/requirement.py
  strictdoc/backend/sdoc/models/sdoc_object.py
  strictdoc/backend/sdoc/models/section.py
Labels: Core roadmap

#1651 Refactoring: requirement.py -> node.py
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  strictdoc/backend/excel/export/excel_generator.py
  strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/reqif/p11_polarion/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/error_handling.py
  strictdoc/backend/sdoc/models/constants.py
  strictdoc/backend/sdoc/models/fragment.py
  strictdoc/backend/sdoc/models/fragment_from_file.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/object.py
  strictdoc/backend/sdoc/models/object_factory.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/validations/requirement.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/analyzers/document_stats.py
  strictdoc/core/analyzers/document_uid_analyzer.py
  strictdoc/core/document_iterator.py
  strictdoc/core/file_traceability_index.py
  strictdoc/core/query_engine/query_object.py
  strictdoc/core/traceability_index.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/section.py
  strictdoc/core/transforms/update_grammar.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/dot/document_dot_generator.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/generators/project_statistics.py
  strictdoc/export/html/renderers/link_renderer.py
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/rst/writer.py
  strictdoc/export/spdx/spdx_generator.py
  strictdoc/export/spdx/spdx_to_sdoc_converter.py
  strictdoc/git/change.py
  strictdoc/git/project_diff_analyzer.py
  strictdoc/server/routers/main_router.py
  tests/integration/scripting_examples/reqif/02_user_provided_example/script.py
  tests/unit/helpers/test_document_builder.py
  tests/unit/strictdoc/backend/sdoc/models/test_requirement.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_grammars.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_includes.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
Labels: Second roadmap

#1653 Refactoring: Requirement -> SDocNode
  docs/sphinx/source/strictdoc_01_user_guide.rst
  docs/strictdoc_01_user_guide.sdoc
  strictdoc/backend/excel/export/excel_generator.py
  strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/reqif/p11_polarion/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/error_handling.py
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/models/constants.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/object_factory.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/validations/requirement.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/analyzers/document_stats.py
  strictdoc/core/analyzers/document_uid_analyzer.py
  strictdoc/core/document_iterator.py
  strictdoc/core/file_traceability_index.py
  strictdoc/core/query_engine/query_object.py
  strictdoc/core/traceability_index.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/section.py
  strictdoc/core/transforms/update_grammar.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/dot/document_dot_generator.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/generators/project_statistics.py
  strictdoc/export/html/renderers/link_renderer.py
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/html/templates/screens/source_file_view/requirement.jinja
  strictdoc/export/rst/writer.py
  strictdoc/export/spdx/spdx_generator.py
  strictdoc/export/spdx/spdx_to_sdoc_converter.py
  strictdoc/git/change.py
  strictdoc/git/project_diff_analyzer.py
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/update_requirement/update_requirement_remove_uid_then_create_new_requirement/test_case.py
  tests/integration/scripting_examples/reqif/02_user_provided_example/script.py
  tests/unit/helpers/test_document_builder.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_grammars.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_includes.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
Labels: Second roadmap

#1654 Refactoring: Section -> SDocSection
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/reqif/p11_polarion/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/models/constants.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/analyzers/document_stats.py
  strictdoc/core/analyzers/document_uid_analyzer.py
  strictdoc/core/document_iterator.py
  strictdoc/core/query_engine/query_object.py
  strictdoc/core/traceability_index.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/delete_section.py
  strictdoc/core/transforms/section.py
  strictdoc/core/transforms/update_free_text.py
  strictdoc/export/dot/document_dot_generator.py
  strictdoc/export/html/form_objects/section_form_object.py
  strictdoc/export/html/generators/project_statistics.py
  strictdoc/export/html/renderers/link_renderer.py
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/rst/writer.py
  strictdoc/export/spdx/spdx_to_sdoc_converter.py
  strictdoc/git/change.py
  strictdoc/git/project_diff_analyzer.py
  strictdoc/server/routers/main_router.py
  tests/integration/options/options_per_document/AUTO_LEVELS/10_option_is_on_but_section_level_is_provided/test.itest
  tests/integration/scripting_examples/reqif/02_user_provided_example/script.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_includes.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
  tools/confluence_html_table_import.py
Labels: Second roadmap

#1667 export/json: basic JSON export
  strictdoc/cli/command_parser_builder.py
  strictdoc/core/actions/export_action.py
  strictdoc/export/json/json_generator.py
  tests/integration/commands/export/json/01_basic_json_export/input1.sdoc
  tests/integration/commands/export/json/01_basic_json_export/input2.sdoc
  tests/integration/commands/export/json/01_basic_json_export/strictdoc.toml
  tests/integration/commands/export/json/01_basic_json_export/test.itest
  tests/integration/commands/export/options/--formats/01_incorrect_format/test.itest
Labels: Core roadmap

#1668 export/dot: disable requirement links
  strictdoc/export/dot/document_dot_generator.py
  strictdoc/export/dot/templates/profile1/top_level.dot
  strictdoc/export/dot/templates/profile2/top_level.dot
  tests/integration/commands/export/dot/01_minimal_document/test.itest
Labels: Second roadmap

#1671 screens/diff: improve the legend with "HEAD vs HEAD+"
  strictdoc/export/html/templates/screens/git/legend.jinja
Labels: Second roadmap

#1672 docs: SDoc grammar DOCUMENT fields: add REQ_PREFIX
  docs/strictdoc_01_user_guide.sdoc
Labels: Second roadmap

#1673 docs: add a note about not detecting .sdoc files in the output/ folder
  docs/strictdoc_01_user_guide.sdoc
Labels: Second roadmap
