Repository strictdoc-project/strictdoc, pull requests merged in 2025-05, with the labels that each got.

#2203 helpers/google_test: improve error message when hitting unexpected content
  strictdoc/helpers/google_test.py
Labels: Second roadmap

#2204 tests/integration: one more JUnit XML sample produced by Google Test
  tests/integration/features/test_reports/junit_xml/gtest/06_user_example_still_does_not_work/.gitignore
  tests/integration/features/test_reports/junit_xml/gtest/06_user_example_still_does_not_work/reports/tests_unit.gtest.junit.xml
  tests/integration/features/test_reports/junit_xml/gtest/06_user_example_still_does_not_work/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/gtest/06_user_example_still_does_not_work/test.itest
  tests/integration/features/test_reports/junit_xml/gtest/06_user_example_still_does_not_work/tests/test1.cpp
Labels: Second roadmap

#2205 commands/manage_autouid: ensure that non-SDoc files are not modified
  strictdoc/commands/manage_autouid_command.py
  tests/integration/features/commands/manage/auto-uid/_cross_cutting/grammar_from_file/02_ignores_junit_xml/test.itest
  tests/integration/features/commands/manage/auto-uid/_cross_cutting/grammar_from_file/02_ignores_junit_xml/tests_unit.gtest.junit.xml
Labels: Second roadmap

#2208 README: remove CI badges
  README.md
Labels: Second roadmap

#2207 Feature: Project statistics: add requirement status breakdown table
  strictdoc/export/html/generators/project_statistics.py
  strictdoc/export/html/generators/view_objects/project_statistics_view_object.py
  strictdoc/export/html/generators/view_objects/project_tree_stats.py
  strictdoc/export/html/templates/components/table_key_value/index.jinja
  strictdoc/export/html/templates/screens/git/changelog_content.jinja
  strictdoc/export/html/templates/screens/project_statistics/main.jinja
  tests/end2end/screens/project_statistics/view_project_statistics/test_case.py
  tests/integration/features/project_statistics/01_statistics_are_generated/test.itest
  tests/integration/features/project_statistics/20_requirement_metric_does_not_include_text_nodes/test.itest
  tests/integration/features/project_statistics/30_requirements_status_breakdown/input.sdoc
  tests/integration/features/project_statistics/30_requirements_status_breakdown/strictdoc.toml
  tests/integration/features/project_statistics/30_requirements_status_breakdown/test.itest
  tools/link_health.py
Labels: Core roadmap

#2215 Code climate: document_grammar: fix no-untyped-def
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/models/model.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/validations/sdoc_validator.py
Labels: Code climate, Second roadmap

#2216 Code climate: .link_health.yml: disable all GitHub links for now
  .link_health.yml
Labels: Code climate, Second roadmap

#2227 tests/end2end: update_node: consolidate Single/MultiChoice-related tests
  tests/end2end/screens/document/create_requirement/_SingleChoice/create_requirement_SingleChoice_field_using_autocomplete/expected_output/document.sdoc
  tests/end2end/screens/document/create_requirement/_SingleChoice/create_requirement_SingleChoice_field_using_autocomplete/input/document.sdoc
  tests/end2end/screens/document/create_requirement/_SingleChoice/create_requirement_SingleChoice_field_using_autocomplete/test_case.py
  tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_must_not_save_INCORRECT_MultipleChoice_value/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_must_not_save_INCORRECT_MultipleChoice_value/input/document.sdoc
  tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_must_not_save_INCORRECT_MultipleChoice_value/test_case.py
  tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_must_sanitize_MultipleChoice_separation/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_must_sanitize_MultipleChoice_separation/input/document.sdoc
  tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_must_sanitize_MultipleChoice_separation/test_case.py
  tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_saves_empty_MultipleChoice_value/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_saves_empty_MultipleChoice_value/input/document.sdoc
  tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_saves_empty_MultipleChoice_value/test_case.py
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_SingleChoice_field_using_autocomplete/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_SingleChoice_field_using_autocomplete/input/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_SingleChoice_field_using_autocomplete/test_case.py
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_must_not_save_INCORRECT_SingleChoice_value/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_must_not_save_INCORRECT_SingleChoice_value/input/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_must_not_save_INCORRECT_SingleChoice_value/test_case.py
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_saves_empty_SingleChoice_value/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_saves_empty_SingleChoice_value/input/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_saves_empty_SingleChoice_value/test_case.py
Labels: Code climate, Second roadmap

#2228 tests/end2end: update node: add test for update of MultipleChoice field
  tests/end2end/screens/document/update_requirement/_SingleChoice/_validation/update_requirement_must_not_save_INCORRECT_SingleChoice_value/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/_validation/update_requirement_must_not_save_INCORRECT_SingleChoice_value/input/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/_validation/update_requirement_must_not_save_INCORRECT_SingleChoice_value/test_case.py
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_basic_update_of_SingleChoice_value/expected_output/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_basic_update_of_SingleChoice_value/input/document.sdoc
  tests/end2end/screens/document/update_requirement/_SingleChoice/update_requirement_basic_update_of_SingleChoice_value/test_case.py
Labels: Second roadmap

#2234 pyproject.toml: switch to html2pdf4doc
  developer/pyinstaller_hooks/hook-html2pdf4doc.py
  pyproject.toml
  strictdoc/export/html/html_generator.py
  strictdoc/export/html/templates/screens/document/pdf/index.jinja
  strictdoc/export/html2pdf/pdf_print_driver.py
  tests/integration/features/html2pdf/01_empty_document/test.itest
  tests/integration/features/html2pdf/02_three_top_level_requirements/test.itest
  tests/integration/features/html2pdf/03_three_documents_with_assets/test.itest
  tests/integration/features/html2pdf/04_composable_document_with_assets/test.itest
  tests/integration/features/html2pdf/05_generate_bundle_document/test.itest
  tests/integration/features/html2pdf/06_system_chromedriver/test.itest
Labels: Second roadmap

#2236 tests/unit: fix a regression due to a recent textX change
  tasks.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
Labels: Second roadmap

#2242 export/html: source file view: fix the entire file marker positioning
  strictdoc/export/html/generators/source_file_view_generator.py
  tests/integration/features/file_traceability/_markers/01_basic_file_marker/file.py
  tests/integration/features/file_traceability/_markers/01_basic_file_marker/input.sdoc
  tests/integration/features/file_traceability/_markers/01_basic_file_marker/strictdoc.toml
  tests/integration/features/file_traceability/_markers/01_basic_file_marker/test.itest
  tests/integration/features/file_traceability/_markers/02_file_marker_regression/file.py
  tests/integration/features/file_traceability/_markers/02_file_marker_regression/input.sdoc
  tests/integration/features/file_traceability/_markers/02_file_marker_regression/strictdoc.toml
  tests/integration/features/file_traceability/_markers/02_file_marker_regression/test.itest
  tests/unit/strictdoc/backend/sdoc_source_code/readers/test_reader_python.py
Labels: Second roadmap

#2244 backend/sdoc: document_grammar: make TEXT node to have Plain style by default
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_02_feature_map.sdoc
  docs/strictdoc_03_faq.sdoc
  docs/strictdoc_20_L1_Open_Requirements_Tool.sdoc
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  pyproject.toml
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/writer.py
  tests/end2end/__init__.py
  tests/end2end/screens/document/create_requirement/_SingleChoice/create_requirement_SingleChoice_field_using_autocomplete/input/document.sdoc
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar.py
Labels: Core roadmap

#2249 UI: Delete node: Validate the removed node recursively
  strictdoc/core/document_iterator.py
  strictdoc/core/traceability_index.py
  strictdoc/core/transforms/delete_requirement.py
  tests/end2end/screens/document/delete_node/_validation/delete_node_must_prevent_deletion_when_children_have_incoming_parent_RELATIONs/expected_output/document.sdoc
  tests/end2end/screens/document/delete_node/_validation/delete_node_must_prevent_deletion_when_children_have_incoming_parent_RELATIONs/input/document.sdoc
  tests/end2end/screens/document/delete_node/_validation/delete_node_must_prevent_deletion_when_children_have_incoming_parent_RELATIONs/test_case.py
  tests/end2end/screens/document/delete_node/_validation/delete_node_must_prevent_deletion_when_incoming_parent_RELATIONs/expected_output/document.sdoc
  tests/end2end/screens/document/delete_node/_validation/delete_node_must_prevent_deletion_when_incoming_parent_RELATIONs/input/document.sdoc
  tests/end2end/screens/document/delete_node/_validation/delete_node_must_prevent_deletion_when_incoming_parent_RELATIONs/test_case.py
  tests/end2end/screens/document/delete_node/_validation/delete_node_that_has_incoming_LINKs/expected_output/document.sdoc
  tests/end2end/screens/document/delete_node/_validation/delete_node_that_has_incoming_LINKs/input/document.sdoc
  tests/end2end/screens/document/delete_node/_validation/delete_node_that_has_incoming_LINKs/test_case.py
  tests/end2end/screens/document/delete_node/_validation/delete_node_with_ANCHOR_that_has_incoming_LINKs/expected_output/document.sdoc
  tests/end2end/screens/document/delete_node/_validation/delete_node_with_ANCHOR_that_has_incoming_LINKs/input/document.sdoc
  tests/end2end/screens/document/delete_node/_validation/delete_node_with_ANCHOR_that_has_incoming_LINKs/test_case.py
  tests/end2end/screens/document/delete_node/delete_node_delete_existing/expected_output/document.sdoc
  tests/end2end/screens/document/delete_node/delete_node_delete_existing/input/document.sdoc
  tests/end2end/screens/document/delete_node/delete_node_delete_existing/test_case.py
  tests/end2end/screens/document/delete_node/delete_node_delete_newly_created/expected_output/document.sdoc
  tests/end2end/screens/document/delete_node/delete_node_delete_newly_created/input/document.sdoc
  tests/end2end/screens/document/delete_node/delete_node_delete_newly_created/test_case.py
  tests/end2end/screens/document/delete_section/_validation/delete_section_that_has_incoming_LINKs/expected_output/document.sdoc
  tests/end2end/screens/document/delete_section/_validation/delete_section_that_has_incoming_LINKs/input/document.sdoc
  tests/end2end/screens/document/delete_section/_validation/delete_section_that_has_incoming_LINKs/test_case.py
Labels: Core roadmap

#2250 backend/sdoc: Prepare automatic migration: [SECTION] -> [[SECTION]]
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/backend/sdoc/reader.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_new_section_composite_syntax.py
Labels: Core roadmap

#2254 Code climate: query_engine: query_object: fix all mypy issues
  .link_health.yml
  strictdoc/core/query_engine/query_object.py
Labels: Code climate

#2255 docs: update Roadmap diagram
  docs/_assets/StrictDoc_Workspace-Roadmap.drawio.png
Labels: Documentation, Core roadmap

#2259 UI: adjust Move Node to [[NODE]]
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/move_node/move_node_basic_moving_DEPRECATED/expected_output/document.sdoc
  tests/end2end/screens/document/move_node/move_node_basic_moving_DEPRECATED/input/document.sdoc
  tests/end2end/screens/document/move_node/move_node_basic_moving_DEPRECATED/test_case.py
  tests/end2end/screens/document/move_node/move_node_move_node_to_composite_node/expected_output/document.sdoc
  tests/end2end/screens/document/move_node/move_node_move_node_to_composite_node/input/document.sdoc
  tests/end2end/screens/document/move_node/move_node_move_node_to_composite_node/test_case.py
Labels: Core roadmap

#2260 docs: document the migration path: [SECTION] -> [[SECTION]]
  docs/strictdoc_01_user_guide.sdoc
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/reader.py
  strictdoc/core/project_config.py
  tasks.py
  tests/integration/features/sdoc/composite_node_migration/01_migration_path_with_project_config_option/input.expected.sdoc
  tests/integration/features/sdoc/composite_node_migration/01_migration_path_with_project_config_option/input.sdoc
  tests/integration/features/sdoc/composite_node_migration/01_migration_path_with_project_config_option/strictdoc.toml
  tests/integration/features/sdoc/composite_node_migration/01_migration_path_with_project_config_option/test.itest
  tests/integration/features/sdoc/composite_node_migration/02_migration_path_included_documents/input.sdoc
  tests/integration/features/sdoc/composite_node_migration/02_migration_path_included_documents/nested.sdoc
  tests/integration/features/sdoc/composite_node_migration/02_migration_path_included_documents/strictdoc.toml
  tests/integration/features/sdoc/composite_node_migration/02_migration_path_included_documents/subnested.expected.sdoc_
  tests/integration/features/sdoc/composite_node_migration/02_migration_path_included_documents/subnested.sdoc
  tests/integration/features/sdoc/composite_node_migration/02_migration_path_included_documents/test.itest
Labels: Core roadmap

#2261 [[NODE]] migration: print [SECTION] deprecation message
  docs/sphinx/source/strictdoc_01_user_guide.rst
  docs/strictdoc_01_user_guide.sdoc
  strictdoc/backend/sdoc/reader.py
  strictdoc/core/traceability_index_builder.py
  tests/end2end/__init__.py
  tests/integration/features/sdoc/composite_node_migration/00_migration_warning_shown_when_no_project_config_option/input.expected.sdoc
  tests/integration/features/sdoc/composite_node_migration/00_migration_warning_shown_when_no_project_config_option/input.sdoc
  tests/integration/features/sdoc/composite_node_migration/00_migration_warning_shown_when_no_project_config_option/strictdoc.toml
  tests/integration/features/sdoc/composite_node_migration/00_migration_warning_shown_when_no_project_config_option/test.itest
Labels: Core roadmap

#2263 [[NODE]] migration: carry over SECTION reset UID behavior
  strictdoc/backend/sdoc/models/model.py
  strictdoc/backend/sdoc/reader.py
  strictdoc/core/analyzers/document_stats.py
  strictdoc/core/analyzers/document_uid_analyzer.py
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid/expected_output/document.sdoc
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid/input/document.sdoc
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid/test_case.py
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid_DEPRECATED/expected_output/document.sdoc
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid_DEPRECATED/input/document.sdoc
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid_DEPRECATED/test_case.py
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid_duplicate_section_title/expected_output/document.sdoc
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid_duplicate_section_title/input/document.sdoc
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid_duplicate_section_title/test_case.py
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid_duplicate_section_title_DEPRECATED/expected_output/document.sdoc
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid_duplicate_section_title_DEPRECATED/input/document.sdoc
  tests/end2end/screens/document/update_section/_autouid/update_node_section_generate_auto_uid_duplicate_section_title_DEPRECATED/test_case.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar.py
Labels: Core roadmap

#2265 Code climate: add custom fixit linting check: StrictDoc_CheckDocstringsRule
  developer/fixit/check_docstrings.py
  pyproject.toml
  requirements.check.txt
  strictdoc/backend/excel/import_/excel_sheet_proxy.py
  strictdoc/backend/sdoc_source_code/reader_c.py
  strictdoc/backend/sdoc_source_code/reader_python.py
  strictdoc/backend/sdoc_source_code/reader_robot.py
  strictdoc/backend/sdoc_source_code/test_reports/robot_xml_reader.py
  strictdoc/git/project_diff_analyzer.py
  tasks.py
Labels: Second roadmap

#2266 docs: update the SDoc markup chapter: [[NODE]]-related updates
  docs/sphinx/source/strictdoc_01_user_guide.rst
  docs/strictdoc_01_user_guide.sdoc
Labels: Core roadmap

#2267 Code climate: add custom fixit linting check: StrictDoc_CheckCommentsRule
  developer/fixit/check_comments.py
  developer/fixit/check_docstrings.py
  pyproject.toml
  tasks.py
Labels: Second roadmap

#2269 code-climate: mypy: address type-arg: SourceFileTraceabilityInfo/Parts
  strictdoc/backend/sdoc_source_code/models/function_range_marker.py
  strictdoc/backend/sdoc_source_code/models/range_marker.py
  strictdoc/backend/sdoc_source_code/models/source_file_info.py
  strictdoc/backend/sdoc_source_code/reader.py
Labels: Second roadmap

#2271 backend/sdoc_source_code: reader_c: fix a small edge case related to code comments
  strictdoc/backend/sdoc_source_code/reader_c.py
  tests/integration/features/test_reports/junit_xml/ctest/05_user_example/test.itest
  tests/integration/features/test_reports/junit_xml/gtest/05_user_example/test.itest
  tests/integration/features/test_reports/junit_xml/gtest/06_user_example_still_does_not_work/test.itest
Labels: Core roadmap

#2270 code-climate: mypy: address type-arg: JSON generator
  strictdoc/export/json/json_generator.py
Labels: Second roadmap

#2264 code-climate: mypy: address type-arg
  strictdoc/export/html/form_objects/grammar_element_form_object.py
  strictdoc/export/html/form_objects/grammar_form_object.py
  strictdoc/export/html/form_objects/included_document_form_object.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/form_objects/section_form_object.py
  strictdoc/helpers/form_data.py
Labels: Second roadmap

#2279 tests/end2end: run each test's SDoc server from its folder, unless specified otherwise
  tests/end2end/server.py
Labels: Second roadmap

#2284 Code climate: Remove unused code
  strictdoc/core/graph/abstract_bucket.py
  strictdoc/core/graph/many_to_many_set.py
  strictdoc/core/graph/one_to_one_dictionary.py
  strictdoc/core/graph_database.py
  strictdoc/core/traceability_index.py
  strictdoc/export/html/generators/view_objects/diff_screen_results_view_object.py
  strictdoc/export/html/generators/view_objects/diff_screen_view_object.py
  strictdoc/export/html/generators/view_objects/document_screen_view_object.py
  strictdoc/export/html/generators/view_objects/search_screen_view_object.py
  strictdoc/export/html/generators/view_objects/source_file_view_object.py
  strictdoc/export/html/generators/view_objects/traceability_matrix_view_object.py
Labels: Code climate, Second roadmap

#2286 parallelizer: improve handling of child processes
  strictdoc/helpers/parallelizer.py
  tests/end2end/exporter.py
Labels: Core roadmap

#2288 tests/end2end: fix copy_stable_link failing when running with code coverage
  tests/end2end/screens/document/copy_stable_link/test_case.py
  tests/end2end/server.py
Labels: Second roadmap

#2289 Code climate: core/file_tree: simplify code, increase code coverage
  strictdoc/backend/sdoc_source_code/coverage_reports/gcov.py
  strictdoc/backend/sdoc_source_code/test_reports/junit_xml_reader.py
  strictdoc/backend/sdoc_source_code/test_reports/robot_xml_reader.py
  strictdoc/core/document_finder.py
  strictdoc/core/file_tree.py
  strictdoc/core/finders/source_files_finder.py
  strictdoc/export/html/generators/view_objects/helpers.py
  strictdoc/export/html/templates/screens/document/_shared/project_tree.jinja
  strictdoc/export/html/templates/screens/git/diff_content.jinja
  strictdoc/export/html/templates/screens/project_index/project_map_file.jinja
  strictdoc/export/html/templates/screens/project_index/project_tree_file.jinja
  strictdoc/export/html/templates/screens/source_file_coverage/file.jinja
  strictdoc/export/html/templates/screens/source_file_coverage/folder.jinja
  tests/unit/strictdoc/core/test_file_tree.py
Labels: Code climate, Second roadmap

#2292 tests/end2end: switch to parallel = true when collecting coverage
  .coveragerc.end2end
  tasks.py
  tests/end2end/screens/document/_cross_cutting/LINK_and_ANCHOR/node/_update/update_node_add_link_to_existing_section_anchor_from_clipboard/test_case.py
  tests/end2end/screens/document/move_node/move_node_basic_moving_DEPRECATED/test_case.py
  tests/end2end/screens/document/move_node/move_node_move_node_to_composite_node/test_case.py
  tests/end2end/server.py
Labels: Core roadmap

#2291 tests/end2end: helpers: ensure that most screens wait better for page load
  tests/end2end/helpers/screens/project_index/screen_project_index.py
  tests/end2end/helpers/screens/project_statistics/project_statistics.py
  tests/end2end/helpers/screens/requirements_coverage/screen_requirements_coverage.py
  tests/end2end/helpers/screens/screen.py
  tests/end2end/helpers/screens/source_coverage/screen_source_coverage.py
Labels: Second roadmap

#2293 tests/end2end: some more stability when running with coverage and without
  tests/end2end/server.py
  tests/unit/strictdoc/helpers/test_string.py
Labels: Second roadmap

#2294 Code climate: remove some unreachable code from coverage
  strictdoc/cli/main.py
  strictdoc/core/actions/import_action.py
  strictdoc/core/query_engine/query_reader.py
  strictdoc/export/html/form_objects/grammar_element_form_object.py
  strictdoc/export/html/form_objects/grammar_form_object.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/form_objects/section_form_object.py
  strictdoc/export/html/generators/view_objects/source_file_view_object.py
  strictdoc/export/rst/document_rst_generator.py
  strictdoc/export/rst/rst_to_html_fragment_writer.py
  strictdoc/export/rst/writer.py
  strictdoc/helpers/coverage.py
  strictdoc/helpers/paths.py
  strictdoc/helpers/rst.py
  strictdoc/helpers/string.py
  strictdoc/server/app.py
  strictdoc/server/server.py
  tests/integration/features/file_traceability/g1_file_types/60_yaml/example.sdoc
  tests/integration/features/file_traceability/g1_file_types/60_yaml/file.yaml
  tests/integration/features/file_traceability/g1_file_types/60_yaml/strictdoc.toml
  tests/integration/features/file_traceability/g1_file_types/60_yaml/test.itest
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar.py
  tests/unit/strictdoc/helpers/test_string.py
  tests/unit/strictdoc/helpers/test_string_safe_acronym.py
Labels: Code climate, Second roadmap

#2295 Code climate: remove some unreachable code from coverage, add missing tests
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc_source_code/caching_reader.py
  strictdoc/cli/main.py
  strictdoc/export/html/generators/view_objects/project_statistics_view_object.py
  strictdoc/export/html/generators/view_objects/traceability_matrix_view_object.py
  strictdoc/export/rst/directives/wildcard_enhanced_image.py
  strictdoc/helpers/parallelizer.py
  strictdoc/server/app.py
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/_validation/update_included_document_validate_title_must_not_be_empty/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/_validation/update_included_document_validate_title_must_not_be_empty/expected_output/fragment.sdoc
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/_validation/update_included_document_validate_title_must_not_be_empty/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/_validation/update_included_document_validate_title_must_not_be_empty/input/fragment.sdoc
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/_validation/update_included_document_validate_title_must_not_be_empty/test_case.py
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/update_included_document_title/expected_output/document.sdoc
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/update_included_document_title/expected_output/fragment.sdoc
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/update_included_document_title/input/document.sdoc
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/update_included_document_title/input/fragment.sdoc
  tests/end2end/screens/document/_cross_cutting/included_documents/_outside_fragment/update_included_document_title/test_case.py
  tests/integration/features/document_fragments/_validations/01_document_file_path_must_be_sdoc/input.sdoc
  tests/integration/features/document_fragments/_validations/01_document_file_path_must_be_sdoc/test.itest
  tests/integration/features/document_fragments/_validations/02_document_file_path_must_be_valid/input.sdoc
  tests/integration/features/document_fragments/_validations/02_document_file_path_must_be_valid/test.itest
  tests/integration/features/document_fragments/_validations/03_document_file_must_be_included_once/input.sdoc
  tests/integration/features/document_fragments/_validations/03_document_file_must_be_included_once/input2.sdoc
  tests/integration/features/document_fragments/_validations/03_document_file_must_be_included_once/nested.sdoc
  tests/integration/features/document_fragments/_validations/03_document_file_must_be_included_once/test.itest
  tests/integration/features/html/parallelization/06_parallelization_sdoc_parsing_problem_in_child_process/test.itest
  tests/unit/strictdoc/backend/sdoc/validations/test_requirement_validations.py
  tests/unit/strictdoc/export/rst/test_rst_to_html_fragment_writer.py
Labels: Second roadmap
