Repository strictdoc-project/strictdoc, pull requests merged in 2025-01, with the labels that each got.

#2053 HTML2PDF: update to include latest fixes, exclude included documents from bundle document
  strictdoc/core/traceability_index.py
  strictdoc/export/html/_static/html2pdf/bundle.js
  tests/integration/features/html2pdf/04_composable_document_with_assets/test.itest
  tests/integration/features/html2pdf/04_composable_document_with_assets/test_bundle_pdf.py
Labels: Core roadmap

#2054 Diff: Recognize when child relations are modified
  strictdoc/git/project_diff_analyzer.py
  tests/integration/features/diff/20__requirements_relations__same_document__add_parent_relation/lhs/input.sdoc
  tests/integration/features/diff/20__requirements_relations__same_document__add_parent_relation/rhs/input.sdoc
  tests/integration/features/diff/20__requirements_relations__same_document__add_parent_relation/strictdoc.toml
  tests/integration/features/diff/20__requirements_relations__same_document__add_parent_relation/test.itest
  tests/integration/features/diff/21__requirements_relations__same_document__remove_parent_relation/lhs/input.sdoc
  tests/integration/features/diff/21__requirements_relations__same_document__remove_parent_relation/rhs/input.sdoc
  tests/integration/features/diff/21__requirements_relations__same_document__remove_parent_relation/strictdoc.toml
  tests/integration/features/diff/21__requirements_relations__same_document__remove_parent_relation/test.itest
  tests/integration/features/diff/22__requirements_relations__two_docs__add_child_relation/lhs/input1.sdoc
  tests/integration/features/diff/22__requirements_relations__two_docs__add_child_relation/lhs/input2.sdoc
  tests/integration/features/diff/22__requirements_relations__two_docs__add_child_relation/rhs/input1.sdoc
  tests/integration/features/diff/22__requirements_relations__two_docs__add_child_relation/rhs/input2.sdoc
  tests/integration/features/diff/22__requirements_relations__two_docs__add_child_relation/strictdoc.toml
  tests/integration/features/diff/22__requirements_relations__two_docs__add_child_relation/test.itest
Labels: Core roadmap

#2055 Bump version to 0.5.0
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/__init__.py
  tests/integration/features/file_traceability/_language_parsers/python/03_python_forward_function/test.itest
  tests/integration/features/file_traceability/_language_parsers/python/04_python_forward_function_in_class/test.itest
Labels: Core roadmap

#2066 Resolves #2065: Silence multiprocessing KeyboardInterrupt traceback
  strictdoc/helpers/parallelizer.py
Labels: Second roadmap

#2069 Use rST admonitions where possible for "Note", "Observation", "Example"
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_11_developer_guide.sdoc
Labels: Documentation, Code climate
