Repository strictdoc-project/strictdoc, pull requests merged in 2025-04, with the labels that each got.

#2125 file_traceability_index: transitively connect test results with requirements through tests
  strictdoc/core/constants.py
  strictdoc/core/file_traceability_index.py
  strictdoc/core/graph/validations.py
  strictdoc/core/traceability_index.py
  strictdoc/core/transforms/update_requirement.py
Labels: Core roadmap

#2127 UI: Source View screen: Final adjustments of the page layout
  strictdoc/backend/sdoc_source_code/models/function_range_marker.py
  strictdoc/backend/sdoc_source_code/models/range_marker.py
  strictdoc/export/html/_static/source.css
  strictdoc/export/html/generators/view_objects/source_file_view_object.py
  strictdoc/export/html/templates/_res/svg_ico16_source_pointer_in.jinja
  strictdoc/export/html/templates/_res/svg_ico16_source_pointer_out.jinja
  strictdoc/export/html/templates/screens/source_file_view/index.jinja
  strictdoc/export/html/templates/screens/source_file_view/main.jinja
  strictdoc/export/html/templates/screens/source_file_view/node_title_for_banner_header.jinja
  strictdoc/export/html/templates/screens/source_file_view/range_button.jinja
  strictdoc/export/html/templates/screens/source_file_view/range_definition.jinja
  strictdoc/export/html/templates/screens/source_file_view/requirement.jinja
Labels: Core roadmap

#2128 UI: Source View screen: Finalise closing range buttons
  strictdoc/export/html/_static/source.css
  strictdoc/export/html/templates/screens/source_file_view/main.jinja
  strictdoc/export/html/templates/screens/source_file_view/range_button.jinja
  strictdoc/export/html/templates/screens/source_file_view/range_definition.jinja
Labels: Core roadmap

#2132 backend/sdoc_source_code: marker_parser: allow "_" characters in UID
  strictdoc/backend/sdoc_source_code/marker_parser.py
  tests/unit/strictdoc/backend/sdoc_source_code/test_marker_parser.py
Labels: Bug

#2135 docs: Machine Identifiers: describe the need to define a grammar
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_02_feature_map.sdoc
Labels: Documentation, Second roadmap

#2136 docs: experimental: JUnit XML + expand on the quality in dev plan
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_24_development_plan.sdoc
Labels: Documentation, Second roadmap

#2138 Code climate: remove dead code related to basic_free_text
  strictdoc/backend/sdoc/models/node.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/templates/screens/document/document/frame_requirement_form.jinja
  strictdoc/export/rst/writer.py
  strictdoc/server/routers/main_router.py
Labels: Code climate, Second roadmap

#2139 Code climate: resolve circular references between SDocDocument and DocumentReference
  strictdoc/backend/sdoc/document_reference.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/document_from_file.py
  strictdoc/core/transforms/section.py
  strictdoc/export/html/renderers/link_renderer.py
Labels: Core roadmap, Second roadmap

#2140 Code climate: backend/sdoc: document: improve including document typing checks
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/model.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/delete_section.py
  strictdoc/core/transforms/section.py
  strictdoc/core/transforms/update_requirement.py
Labels: Code climate, Second roadmap

#2141 Code climate: improve assert_cast to tell mypy about the casted type
  strictdoc/backend/sdoc/models/node.py
  strictdoc/core/file_traceability_index.py
  strictdoc/core/transforms/section.py
  strictdoc/helpers/cast.py
  tasks.py
Labels: Code climate, Core roadmap

#2145 export/html: --included-documents: display or not display consistently
  strictdoc/core/document_tree.py
  strictdoc/export/html/generators/view_objects/document_screen_view_object.py
  strictdoc/export/html/generators/view_objects/helpers.py
  strictdoc/export/html/generators/view_objects/project_tree_view_object.py
  strictdoc/export/html/templates/screens/document/_shared/project_tree.jinja
  strictdoc/export/html/templates/screens/document/_shared/project_tree_child_documents.jinja
  strictdoc/export/html/templates/screens/project_index/main.jinja
  strictdoc/export/html/templates/screens/project_index/project_tree.jinja
  strictdoc/export/html/templates/screens/project_index/project_tree_folder.jinja
  tests/integration/features/document_fragments/--included-documents/included_documents_option_not_provided/_assets/file.svg
  tests/integration/features/document_fragments/--included-documents/included_documents_option_not_provided/input.sdoc
  tests/integration/features/document_fragments/--included-documents/included_documents_option_not_provided/nested/nested.sdoc
  tests/integration/features/document_fragments/--included-documents/included_documents_option_not_provided/nested/subnested/subnested.sdoc
  tests/integration/features/document_fragments/--included-documents/included_documents_option_not_provided/test.itest
  tests/integration/features/document_fragments/--included-documents/included_documents_option_provided/_assets/file.svg
  tests/integration/features/document_fragments/--included-documents/included_documents_option_provided/input.sdoc
  tests/integration/features/document_fragments/--included-documents/included_documents_option_provided/nested/nested.sdoc
  tests/integration/features/document_fragments/--included-documents/included_documents_option_provided/nested/subnested/subnested.sdoc
  tests/integration/features/document_fragments/--included-documents/included_documents_option_provided/test.itest
  tests/integration/features/document_fragments/30_multiple_inclusion_of_document/input1.sdoc
  tests/integration/features/document_fragments/30_multiple_inclusion_of_document/input2.sdoc
  tests/integration/features/document_fragments/30_multiple_inclusion_of_document/test.itest
Labels: Second roadmap

#2149 project_statistics: more precise calculation of statistics for REQUIREMENT
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  strictdoc/core/query_engine/query_object.py
  strictdoc/export/html/generators/project_statistics.py
  tests/integration/features/project_statistics/20_requirement_metric_does_not_include_text_nodes/input.sdoc
  tests/integration/features/project_statistics/20_requirement_metric_does_not_include_text_nodes/strictdoc.toml
  tests/integration/features/project_statistics/20_requirement_metric_does_not_include_text_nodes/test.itest
Labels: Core roadmap

#2150 Bump version to 0.8.0
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/__init__.py
Labels: Core roadmap

#2152 pdf export: fix pdf export with pictures
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/_export_to_pdf/export_to_pdf_with_picture/_assets/picture.svg
  tests/end2end/screens/document/_export_to_pdf/export_to_pdf_with_picture/document.sdoc
  tests/end2end/screens/document/_export_to_pdf/export_to_pdf_with_picture/strictdoc.toml
  tests/end2end/screens/document/_export_to_pdf/export_to_pdf_with_picture/test_case.py
Labels: Second roadmap

#2160 Code climate: lint/ruff: activate many checks from the D group
  ruff.toml
  strictdoc/backend/excel/import_/excel_sheet_proxy.py
  strictdoc/helpers/ordered_set.py
  tests/end2end/helpers/components/node/document_root.py
  tests/end2end/helpers/components/node/node.py
  tests/end2end/helpers/components/node/requirement.py
  tests/end2end/helpers/screens/screen.py
  tests/integration/features/file_traceability/_language_parsers/python/05_python_class/file.py
  tests/integration/features/file_traceability/_language_parsers/python/05_python_class/test.itest
  tests/integration/features/file_traceability/file_roles/01_relations_with_role/file.py
  tests/integration/features/file_traceability/file_roles/01_relations_with_role/test.itest
  tools/link_health.py
Labels: Code climate, Second roadmap

#2161 backend/sdoc_source_code: parse multiline @relation markers
  strictdoc/backend/sdoc_source_code/helpers/comment_preprocessor.py
  strictdoc/backend/sdoc_source_code/marker_parser.py
  strictdoc/backend/sdoc_source_code/reader.py
  strictdoc/backend/sdoc_source_code/reader_c.py
  strictdoc/backend/sdoc_source_code/reader_python.py
  strictdoc/core/file_traceability_index.py
  tests/unit/strictdoc/backend/sdoc_source_code/helpers/test_comment_preprocessor.py
  tests/unit/strictdoc/backend/sdoc_source_code/readers/test_reader_c.py
  tests/unit/strictdoc/backend/sdoc_source_code/readers/test_reader_cpp.py
  tests/unit/strictdoc/backend/sdoc_source_code/readers/test_reader_general.py
  tests/unit/strictdoc/backend/sdoc_source_code/readers/test_reader_python.py
  tests/unit/strictdoc/backend/sdoc_source_code/test_marker_parser.py
Labels: Core roadmap

#2164 docs: update Roadmap
  docs/_assets/StrictDoc_Workspace-Roadmap.drawio.png
Labels: Documentation, Core roadmap

#2176 docs: update an outdated/migrated link
  docs/strictdoc_03_faq.sdoc
Labels: Second roadmap

#2177 export/html: Update base.css
  strictdoc/export/html/_static/base.css
Labels: Second roadmap

#2178 tasks: calculate code coverage for all test groups
  .coveragerc.end2end
  .coveragerc.integration
  .coveragerc.unit
  .coveragerc.unit_server
  strictdoc/cli/main.py
  strictdoc/export/html2pdf/pdf_print_driver.py
  strictdoc/helpers/coverage.py
  strictdoc/server/app.py
  tasks.py
  tests/end2end/conftest.py
  tests/end2end/sdoc_test_environment.py
  tests/end2end/server.py
  tests/integration/lit.cfg
Labels: Core roadmap

#2181 Read the Docs: use the nightly version of strictdoc to generate HTML
  .readthedocs.yaml
Labels: Second roadmap

#2182 Code climate: backend/sdoc: free_text: remove unused code
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/models/free_text.py
  strictdoc/core/traceability_index.py
  strictdoc/export/json/json_generator.py
  tests/unit/strictdoc/backend/sdoc/test_free_text_reader.py
Labels: Code climate, Second roadmap

#2183 Code climate: traceability_index: remove unused code
  strictdoc/core/traceability_index.py
  strictdoc/helpers/math.py
  tests/unit/strictdoc/helpers/test_math.py
Labels: Code climate, Second roadmap

#2184 Code climate: sdoc_source_code/reader_c: rewrite some missing coverage code
  strictdoc/backend/sdoc/models/inline_link.py
  strictdoc/backend/sdoc_source_code/reader_c.py
  strictdoc/backend/sdoc_source_code/reader_python.py
  strictdoc/helpers/auto_described.py
  tests/unit/strictdoc/backend/sdoc_source_code/readers/test_reader_c.py
Labels: Code climate, Second roadmap

#2185 Code climate: helpers/coverage: exclude dead code from code coverage
  strictdoc/core/traceability_index.py
  strictdoc/export/html/generators/view_objects/document_screen_view_object.py
  strictdoc/helpers/coverage.py
  tasks.py
Labels: Code climate, Second roadmap

#2187 Code climate: main, environment, etc: exclude unreachable code from coverage
  .coveragerc.end2end
  .coveragerc.integration
  .coveragerc.unit
  .coveragerc.unit_server
  strictdoc/cli/main.py
  strictdoc/core/environment.py
Labels: Code climate, Second roadmap

#2188 Code climate: exclude more unreachable code from coverage, remove unused code
  .coveragerc.end2end
  .coveragerc.integration
  .coveragerc.unit
  .coveragerc.unit_server
  strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/sdoc/models/document_view.py
  strictdoc/backend/sdoc/models/model.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/reference.py
  strictdoc/backend/sdoc_source_code/processors/general_language_marker_processors.py
  strictdoc/backend/sdoc_source_code/reader.py
  strictdoc/cli/main.py
  strictdoc/core/document_finder.py
  strictdoc/core/document_iterator.py
  strictdoc/core/document_meta.py
  strictdoc/core/file_tree.py
  strictdoc/core/graph/abstract_bucket.py
  strictdoc/core/graph/many_to_many_set.py
  strictdoc/core/query_engine/query_object.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/section.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/html/document_type.py
  strictdoc/export/html/html_templates.py
  strictdoc/export/html/renderers/link_renderer.py
  strictdoc/export/html/renderers/markup_renderer.py
  strictdoc/export/json/json_generator.py
  strictdoc/export/rst/writer.py
  strictdoc/export/spdx/spdx_generator.py
  strictdoc/helpers/cast.py
  strictdoc/helpers/math.py
  strictdoc/helpers/parallelizer.py
  strictdoc/server/routers/main_router.py
Labels: Code climate, Second roadmap

#2189 Code climate: fix linting issues and remove unreachable/unused code
  strictdoc/backend/sdoc/models/type_system.py
  strictdoc/core/file_dependency_manager.py
  strictdoc/export/html/generators/project_statistics.py
  strictdoc/export/html/generators/source_file_coverage.py
  strictdoc/export/html/generators/source_file_view_generator.py
  strictdoc/helpers/diff.py
  strictdoc/server/error_object.py
  tests/unit/strictdoc/helpers/test_string.py
Labels: Code climate, Second roadmap

#2190 Code climate: backend/sdoc/writer: remove unused code
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/project_config.py
  strictdoc/export/json/json_generator.py
  strictdoc/git/change.py
  strictdoc/helpers/form_data.py
  tasks.py
Labels: Code climate, Second roadmap

#2191 Code climate: .coveragerc.combined: set a limit for the combined code coverage
  .coveragerc.combined
  strictdoc/export/html/document_type.py
  tasks.py
Labels: Code climate, Second roadmap

#2194 backend/sdoc, UI: enable composite requirements adding
  strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
  strictdoc/backend/reqif/p01_sdoc/reqif_to_sdoc_converter.py
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/grammar/grammar_grammar.py
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/models/model.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/document_iterator.py
  strictdoc/core/transforms/create_requirement.py
  strictdoc/core/transforms/delete_requirement.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/html/form_objects/grammar_element_form_object.py
  strictdoc/export/html/templates/components/node/node_controls/index.jinja
  strictdoc/export/spdx/spdx_to_sdoc_converter.py
  tests/end2end/screens/document/create_requirement/_arbitrary_elements/create_requirement_create_test_element_before_test_element/test_case.py
  tests/end2end/screens/document/create_requirement/create_three_nested_requirements/expected_output/document.sdoc
  tests/end2end/screens/document/create_requirement/create_three_nested_requirements/input/document.sdoc
  tests/end2end/screens/document/create_requirement/create_three_nested_requirements/test_case.py
  tests/integration/scripting_examples/reqif/02_user_provided_example/script.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_grammars.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar.py
Labels: Core roadmap

#2195 tests: sdoc_source_code: test for reading markers with underscores
  tests/unit/strictdoc/backend/sdoc_source_code/readers/test_reader_c.py
Labels: Core roadmap

#2198 backend/sdoc: allows slashes in the node UID and MultipleChoice fields
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/validations/sdoc_validator.py
  strictdoc/cli/main.py
  strictdoc/commands/manage_autouid_command.py
  strictdoc/core/document_meta.py
  strictdoc/core/project_config.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/export/spdx/spdx_generator.py
  tests/unit/helpers/document_builder.py
  tests/unit/helpers/fake_document_meta.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar.py
  tests/unit/strictdoc/core/test_traceability_index.py
  tests/unit/strictdoc/core/test_traceability_index_cycles.py
  tests/unit/strictdoc/core/transforms/test_update_requirement.py
Labels: Second roadmap

#2199 backend/sdoc: allow spaces, colons, underscores, dashes in the UID and MultipleChoice fields
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/validations/sdoc_validator.py
  tests/integration/features/document_grammar/type_system/tag/validation/01_invalid_value/input.sdoc
  tests/integration/features/document_grammar/type_system/tag/validation/01_invalid_value/test.itest
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough_grammar.py
Labels: Second roadmap

#2200 backend/sdoc: prepare model for [[SECTION]] migration
  strictdoc/backend/sdoc/grammar/grammar.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/server/reload_config.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
Labels: Core roadmap
