Repository strictdoc-project/strictdoc, pull requests merged in 2025-08, with the labels that each got.

#2417 docs: add instructions for nix
  docs/strictdoc_01_user_guide.sdoc
Labels: Documentation, Second roadmap

#2423 feat(tools): Python script to export ECSS EARM Excel to SDoc files
  tasks.py
  tools/ecss/import_ecss_earm_excel.py
Labels: Core roadmap

#2427 docs: add links to the slide deck
  README.md
  docs/strictdoc_03_faq.sdoc
Labels: Documentation, Core roadmap

#2430 UI: fix math equation numbering
  strictdoc/export/html/templates/screens/document/document/index.jinja
  strictdoc/export/rst/directives/sphinx_style_math.py
  strictdoc/export/rst/rst_to_html_fragment_writer.py
  tests/integration/features/mathjax/03_mathjax_enabled_math_block/input.sdoc
  tests/integration/features/mathjax/03_mathjax_enabled_math_block/test.itest
Labels: Core roadmap

#2437 test(integration): add a test case that works with a C++ test function
  strictdoc/core/file_traceability_index.py
  tests/integration/features/source_code_traceability/_source_nodes/03_cpp_test_function_with_macro_name/input.sdoc
  tests/integration/features/source_code_traceability/_source_nodes/03_cpp_test_function_with_macro_name/strictdoc.toml
  tests/integration/features/source_code_traceability/_source_nodes/03_cpp_test_function_with_macro_name/test.itest
  tests/integration/features/source_code_traceability/_source_nodes/03_cpp_test_function_with_macro_name/test_specification.sdoc
  tests/integration/features/source_code_traceability/_source_nodes/03_cpp_test_function_with_macro_name/tests/file.cpp
Labels: Second roadmap

#2441 Bump version to 0.11.0
  docs/strictdoc_04_release_notes.sdoc
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  strictdoc/__init__.py
  strictdoc/backend/sdoc/models/document.py
  tasks.py
Labels: Core roadmap

#2442 refactor(anchors): skip auto-ID in node anchors
  strictdoc/export/html/_static/controllers/anchor_controller.js
  strictdoc/export/html/templates/components/anchor/index.jinja
Labels: Second roadmap

#2446 fix(HTML): improve how the relation fields are printed
  strictdoc/export/html/templates/components/node_field/files/index.jinja
  strictdoc/export/html/templates/components/node_field/links/index.jinja
Labels: Core roadmap
