Repository strictdoc-project/strictdoc, pull requests merged in 2025-03, with the labels that each got.

#2094 CI: GitHub CI Action for Docker-based workflow
  .github/workflows/docker.yml
  Dockerfile
  pyproject.toml
  tasks.py
Labels: Second roadmap

#2095 docs: add VERSION and DATE to every document's meta
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_02_feature_map.sdoc
  docs/strictdoc_03_faq.sdoc
  docs/strictdoc_04_release_notes.sdoc
  docs/strictdoc_05_troubleshooting.sdoc
  docs/strictdoc_10_contributing.sdoc
  docs/strictdoc_11_developer_guide.sdoc
  docs/strictdoc_20_L1_Open_Requirements_Tool.sdoc
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  docs/strictdoc_24_development_plan.sdoc
  docs/strictdoc_25_design.sdoc
  docs/strictdoc_28_Backlog.sdoc
  docs/strictdoc_30_credits.sdoc
  docs_extra/DO178_requirements.sdoc
  docs_extra/Zephyr_requirements.sdoc
Labels: Second roadmap

#2098 Bump version to 0.7.0
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/__init__.py
Labels: Core roadmap

#2101 tasks_wine: remove the file from the repository
  tasks_wine.py
Labels: Second roadmap

#2102 server: expose "host" argument to the CLI, merge server config into project config
  docs/strictdoc_01_user_guide.sdoc
  docs/strictdoc_04_release_notes.sdoc
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  strictdoc/cli/cli_arg_parser.py
  strictdoc/cli/command_parser_builder.py
  strictdoc/core/project_config.py
  strictdoc/helpers/net.py
  strictdoc/server/app.py
  strictdoc/server/main.py
  strictdoc/server/routers/main_router.py
  strictdoc/server/server.py
  tasks.py
  tests/integration/features/commands/server/validation/malformed_host/test.itest
  tests/unit/strictdoc/helpers/test_net.py
  tests/unit_server/strictdoc/server/01_hello_world/test_01_hello_world.py
  tests/unit_server/strictdoc/server/02_export_document_to_reqif/test_02_export_document_to_reqif.py
Labels: Core roadmap

#2103 Code climate: Confluence HTML import: fix bs4 deprecation warnings
  tools/confluence_html_table_import.py
Labels: Second roadmap

#2109 tests: generate JUnit XML test reports for all test groups
  strictdoc.toml
  tasks.py
  tests/integration/features/test_reports/junit_xml/lit/01_minimal_document/input/input.sdoc
  tests/integration/features/test_reports/junit_xml/lit/01_minimal_document/input/reports/tests_integration.xml
  tests/integration/features/test_reports/junit_xml/lit/01_minimal_document/input/tests/test.ignored.itest
  tests/integration/features/test_reports/junit_xml/lit/01_minimal_document/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/lit/01_minimal_document/test.itest
  tests/integration/lit.cfg
Labels: Core roadmap

#2111 docs: add notes about the groups.io mailing list and the Office Hours
  docs/_assets/StrictDoc_Workspace-Roadmap.drawio.png
  docs/strictdoc_01_user_guide.sdoc
Labels: Documentation, Core roadmap

#2112 Fix: Prevent .copy_to_clipboard-button from receiving hover
  strictdoc/export/html/_static/element.css
Labels: Core roadmap

#2114 export/html: Fix: Prevent partial cropping of interface buttons
  drafts/requirements/strictdoc.toml
  drafts/rst_examples.sdoc
  drafts/strictdoc_low_level_requirements.sdoc_.sdoc
  strictdoc/export/html/_static/content.css
Labels: UI/UX, Second roadmap

#2116 backend/sdoc_source_code: JUnit XML test report reader (multiple results test)
  tests/integration/features/test_reports/junit_xml/gtest/01_passed_test/.gitignore
  tests/integration/features/test_reports/junit_xml/gtest/01_passed_test/docs/input.sdoc
  tests/integration/features/test_reports/junit_xml/gtest/01_passed_test/reports/tests_unit.gtest.junit.xml
  tests/integration/features/test_reports/junit_xml/gtest/01_passed_test/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/gtest/01_passed_test/test.itest
  tests/integration/features/test_reports/junit_xml/gtest/01_passed_test/tests/test.cpp
  tests/integration/features/test_reports/junit_xml/gtest/04_multiple_tests/.gitignore
  tests/integration/features/test_reports/junit_xml/gtest/04_multiple_tests/docs/input.sdoc
  tests/integration/features/test_reports/junit_xml/gtest/04_multiple_tests/reports/tests_unit.gtest.junit.xml
  tests/integration/features/test_reports/junit_xml/gtest/04_multiple_tests/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/gtest/04_multiple_tests/test.itest
  tests/integration/features/test_reports/junit_xml/gtest/04_multiple_tests/tests/test1.cpp
  tests/integration/features/test_reports/junit_xml/gtest/04_multiple_tests/tests/test2.cpp
Labels: Core roadmap

#2120 backend/sdoc_source_code: JUnit XML: recognize Google Test's TEST/TEST_F/TEST_P
  strictdoc/backend/sdoc_source_code/reader_c.py
  strictdoc/backend/sdoc_source_code/test_reports/junit_xml_reader.py
  strictdoc/core/file_traceability_index.py
  strictdoc/core/traceability_index.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/helpers/google_test.py
  strictdoc/helpers/ordered_set.py
  tests/integration/features/test_reports/junit_xml/ctest/01_passed_test/.gitignore
  tests/integration/features/test_reports/junit_xml/ctest/01_passed_test/docs/input.sdoc
  tests/integration/features/test_reports/junit_xml/ctest/01_passed_test/reports/tests_unit.ctest.junit.xml
  tests/integration/features/test_reports/junit_xml/ctest/01_passed_test/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/ctest/01_passed_test/test.itest
  tests/integration/features/test_reports/junit_xml/ctest/01_passed_test/tests/test.cpp
  tests/integration/features/test_reports/junit_xml/ctest/02_failed_test/.gitignore
  tests/integration/features/test_reports/junit_xml/ctest/02_failed_test/docs/input.sdoc
  tests/integration/features/test_reports/junit_xml/ctest/02_failed_test/reports/tests_unit.ctest.junit.xml
  tests/integration/features/test_reports/junit_xml/ctest/02_failed_test/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/ctest/02_failed_test/test.itest
  tests/integration/features/test_reports/junit_xml/ctest/02_failed_test/tests/test.cpp
  tests/integration/features/test_reports/junit_xml/ctest/03_skipped_test/.gitignore
  tests/integration/features/test_reports/junit_xml/ctest/03_skipped_test/docs/input.sdoc
  tests/integration/features/test_reports/junit_xml/ctest/03_skipped_test/reports/tests_unit.ctest.junit.xml
  tests/integration/features/test_reports/junit_xml/ctest/03_skipped_test/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/ctest/03_skipped_test/test.itest
  tests/integration/features/test_reports/junit_xml/ctest/03_skipped_test/tests/test.cpp
  tests/integration/features/test_reports/junit_xml/ctest/04_multiple_tests/.gitignore
  tests/integration/features/test_reports/junit_xml/ctest/04_multiple_tests/docs/input.sdoc
  tests/integration/features/test_reports/junit_xml/ctest/04_multiple_tests/reports/tests_unit.ctest.junit.xml
  tests/integration/features/test_reports/junit_xml/ctest/04_multiple_tests/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/ctest/04_multiple_tests/test.itest
  tests/integration/features/test_reports/junit_xml/ctest/04_multiple_tests/tests/test1.cpp
  tests/integration/features/test_reports/junit_xml/ctest/04_multiple_tests/tests/test2.cpp
  tests/integration/features/test_reports/junit_xml/ctest/05_user_example/.gitignore
  tests/integration/features/test_reports/junit_xml/ctest/05_user_example/reports/tests_unit.ctest.junit.xml
  tests/integration/features/test_reports/junit_xml/ctest/05_user_example/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/ctest/05_user_example/test.itest
  tests/integration/features/test_reports/junit_xml/ctest/05_user_example/tests/test1.cpp
  tests/integration/features/test_reports/junit_xml/gtest/05_user_example/.gitignore
  tests/integration/features/test_reports/junit_xml/gtest/05_user_example/reports/tests_unit.gtest.junit.xml
  tests/integration/features/test_reports/junit_xml/gtest/05_user_example/strictdoc.toml
  tests/integration/features/test_reports/junit_xml/gtest/05_user_example/test.itest
  tests/integration/features/test_reports/junit_xml/gtest/05_user_example/tests/test1.cpp
  tests/unit/strictdoc/backend/sdoc_source_code/test_reports/test_junit_xml_reader_ctest.py
  tests/unit/strictdoc/helpers/test_google_test.py
Labels: Core roadmap
