Repository strictdoc-project/strictdoc, pull requests merged in 2025-02, with the labels that each got.

#2074 html2pdf: switch to html2print pip package
  .github/workflows/periodic-integration-test.yml
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  pyproject.toml
  strictdoc/core/environment.py
  strictdoc/export/html/tools/html_embedded.py
  strictdoc/export/html2pdf/html2pdf.py
  strictdoc/export/html2pdf/html2pdf_generator.py
  strictdoc/export/html2pdf/pdf_print_driver.py
  tasks.py
  tests/end2end/helpers/screens/search/search.py
  tests/integration/features/html2pdf/01_empty_document/test.itest
  tests/integration/features/html2pdf/02_three_top_level_requirements/test.itest
  tests/integration/features/html2pdf/03_three_documents_with_assets/test.itest
  tests/integration/features/html2pdf/04_composable_document_with_assets/test.itest
  tests/integration/features/html2pdf/05_generate_bundle_document/test.itest
  tests/integration/features/html2pdf/06_system_chromedriver/test.itest
Labels: Core roadmap

#2076 Revert "tests/end2end: disable HTML2PDF test on macOS for now"
  strictdoc/export/html2pdf/pdf_print_driver.py
  strictdoc/server/routers/main_router.py
  tests/end2end/screens/document/_export_to_pdf/export_to_pdf_basic/test_case.py
Labels: Second roadmap

#2082 Bump version to 0.6.0
  docs/_assets/StrictDoc_Workspace-Roadmap.drawio.png
  docs/strictdoc_04_release_notes.sdoc
  strictdoc/__init__.py
  tasks.py
  tests/integration/features/html/parallelization/06_parallelization_sdoc_parsing_problem_in_child_process/test.itest
Labels: Core roadmap

#2077 server, UI: add autocomplete for UIDs when editing relations
  strictdoc/export/html/_static/controllers/autocompletable_field_controller.js
  strictdoc/export/html/_static/form.css
  strictdoc/export/html/templates/autocomplete/uid/stream_autocomplete_uid.jinja.html
  strictdoc/export/html/templates/components/form/field/autocompletable/index.jinja
  strictdoc/export/html/templates/components/form/row/row_with_relation.jinja
  strictdoc/export/html/templates/screens/document/document/frame_requirement_form.jinja
  strictdoc/export/html/templates/screens/document/document/index.jinja
  strictdoc/server/routers/main_router.py
  tests/end2end/helpers/form/form.py
  tests/end2end/helpers/screens/document/form_edit_requirement.py
  tests/end2end/screens/document/create_requirement/_relations/create_requirement_with_relation_using_uid_autocomplete/expected_output/document.sdoc
  tests/end2end/screens/document/create_requirement/_relations/create_requirement_with_relation_using_uid_autocomplete/input/document.sdoc
  tests/end2end/screens/document/create_requirement/_relations/create_requirement_with_relation_using_uid_autocomplete/test_case.py
  tests/integration/html_markup_validator.py
Labels: Core roadmap

#2084 docs: update the autocompletion requirement, update release notes
  docs/strictdoc_04_release_notes.sdoc
  docs/strictdoc_21_L2_StrictDoc_Requirements.sdoc
  docs/strictdoc_28_Backlog.sdoc
Labels: Documentation, Core roadmap

#2087 file_traceability: support identical function prototypes in separate files
  strictdoc/__init__.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/core/file_traceability_index.py
Labels: Core roadmap

#2090 Code climate: Improve the type system for the SDoc core classes
  strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
  strictdoc/backend/sdoc/models/anchor.py
  strictdoc/backend/sdoc/models/any_node.py
  strictdoc/backend/sdoc/models/document.py
  strictdoc/backend/sdoc/models/document_from_file.py
  strictdoc/backend/sdoc/models/document_grammar.py
  strictdoc/backend/sdoc/models/model.py
  strictdoc/backend/sdoc/models/node.py
  strictdoc/backend/sdoc/models/object.py
  strictdoc/backend/sdoc/models/section.py
  strictdoc/backend/sdoc/processor.py
  strictdoc/backend/sdoc/writer.py
  strictdoc/core/document_iterator.py
  strictdoc/core/query_engine/query_object.py
  strictdoc/core/traceability_index.py
  strictdoc/core/traceability_index_builder.py
  strictdoc/core/transforms/delete_requirement.py
  strictdoc/core/transforms/section.py
  strictdoc/core/transforms/update_requirement.py
  strictdoc/export/html/form_objects/requirement_form_object.py
  strictdoc/export/html/generators/view_objects/search_screen_view_object.py
  strictdoc/export/html/renderers/link_renderer.py
  strictdoc/server/routers/main_router.py
  tests/unit/strictdoc/backend/sdoc/test_dsl_parent_document_assignment.py
  tests/unit/strictdoc/core/transforms/test_update_requirement.py
Labels: Second roadmap

#2092 Dockerfile: Switch the image to Ubuntu 24, install Chrome
  Dockerfile
Labels: Core roadmap

#2093 HTML2PDF: update to a newer version
  pyproject.toml
  strictdoc/export/html2pdf/pdf_print_driver.py
Labels: Core roadmap
